unit uasp_s2;
{Copyright (c) 1997 Paul D. Fernhout and Cynthia F. Kurtz All rights reserved
http://www.gardenwithinsight.com. See the license file for details on redistribution.
=====================================================================================
DO NOT EDIT THIS FILE. It was generated by the tab2asp program from aspects.tab.
uasp_s2: Aspect creation for soil patch (part 2).}

interface

uses uaspects;

procedure SoilPatch_createAspects2(aspectManager: GsAspectManager);

implementation

procedure SoilPatch_createAspects2(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowFlatCropResidueToDecay',
      'Allow decay of flat residue',
      5531, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowFlatCropResidueToDecay]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowFreshNMineralization',
      'Allow mineralization of fresh organic N',
      5532, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowFreshNMineralization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowFreshPMineralization',
      'Allow mineralization of fresh organic P',
      5533, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowFreshPMineralization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowLabileAndMineralPFlow',
      'Allow flow between labile and mineral P',
      5534, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowLabileAndMineralPFlow]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowLabilePLossInPercolation',
      'Allow labile P loss in percolation',
      5535, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowLabilePLossInPercolation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowLabilePLossInRunoff',
      'Allow labile P loss in runoff',
      5536, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowLabilePLossInRunoff]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowLateralFlow',
      'Allow lateral flow',
      5537, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowLateralFlow]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateLossInLateralFlow',
      'Allow nitrate loss in lateral flow',
      5538, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateLossInLateralFlow]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateLossInPercolation',
      'Allow nitrate loss in percolation',
      5539, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateLossInPercolation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateLossInRunoff',
      'Allow nitrate loss in runoff',
      5540, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateLossInRunoff]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateToEnterSoilInIrrigationWater',
      'Allow nitrate to enter soil in irrigation water',
      5541, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateToEnterSoilInIrrigationWater]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateToEnterSoilInRainfall',
      'Allow nitrate to enter soil in rainfall',
      5542, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateToEnterSoilInRainfall]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrateToMoveToTopSoilLayerByEvaporation',
      'Allow nitrate to move to top soil layer from evaporation',
      5543, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrateToMoveToTopSoilLayerByEvaporation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNitrification',
      'Allow nitrification (ammonia to nitrate)',
      5544, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNitrification]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowNUptakeByPlants',
      'Allow N uptake by plants',
      5545, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowNUptakeByPlants]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowPercolation',
      'Allow percolation',
      5546, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowPercolation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowPlantTranspiration',
      'Allow plant transpiration',
      5547, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowPlantTranspiration]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowPrecipitationToReachPatch',
      'Allow precipitation to reach soil patch',
      5548, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowPrecipitationToReachPatch]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowPUptakeByPlants',
      'Allow P uptake by plants',
      5549, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowPUptakeByPlants]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowRidgeSettlingFromRainfall',
      'Allow ridge settling from rainfall',
      5550, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowRidgeSettlingFromRainfall]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowRunoff',
      'Allow runoff from rainfall',
      5551, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowRunoff]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowRunoffFromIrrigation',
      'Allow runoff from irrigation',
      5552, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowRunoffFromIrrigation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowSnowMelt',
      'Allow snowmelt',
      5553, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowSnowMelt]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowSoilEvaporation',
      'Allow soil evaporation',
      5554, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowSoilEvaporation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowSoilSettlingFromRain',
      'Allow soil settling from rain',
      5555, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowSoilSettlingFromRain]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowStandingDeadToDecayToResidue',
      'Allow decay of standing dead plant material to flat residue',
      5556, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowStandingDeadToDecayToResidue]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowVolatilization',
      'Allow volatilization (loss of ammonia)',
      5557, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowVolatilization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowWaterErosionFromRunoff',
      'Allow water erosion from runoff from rainfall',
      5558, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowWaterErosionFromRunoff]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowWaterErosionFromRunoffFromIrrigation',
      'Allow water erosion from runoff from irrigation',
      5559, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowWaterErosionFromRunoffFromIrrigation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowWindErosion',
      'Allow wind erosion',
      5560, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowWindErosion]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoFertilization',
      'Auto fertilize',
      5561, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAutoFertilization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoHarvest',
      'Auto harvest',
      5562, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAutoHarvest]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoIrrigation',
      'Auto irrigate',
      5563, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAutoIrrigation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoMaintainDrainageSystem',
      'Auto-maintain drainage system',
      5564, 8, 1, false, 2, 
      1, 'options[kSoilOptionsAutoMaintainDrainageSystem]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoMaintainFurrowDikes',
      'Auto-maintain furrow dikes',
      5565, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAutoMaintainFurrowDikes]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAutoPHControl',
      'Auto-maintain pH',
      5566, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAutoPHControl]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsUpdateAlbedo',
      'Update soil albedo',
      5567, 8, 1, false, 1, 
      1, 'options[kSoilOptionsUpdateAlbedo]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsUpdateSoilCoverIndex',
      'Update soil cover index',
      5568, 8, 1, false, 1, 
      1, 'options[kSoilOptionsUpdateSoilCoverIndex]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsUpdateSoilTemperature',
      'Update soil temperature',
      5569, 8, 1, false, 1, 
      1, 'options[kSoilOptionsUpdateSoilTemperature]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsUpdateWaterTableDepth',
      'Update water table depth',
      5570, 8, 1, false, 1, 
      1, 'options[kSoilOptionsUpdateWaterTableDepth]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicMatterAdsorbedToSediment_kgPha',
      'Organic matter lost in eroded soil today',
      5571, 1, 1, true, 4, 
      2, 'movement.organicMatterAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicMatterChangeFromMineralization_tPha',
      'Organic matter change from mineralization today',
      5572, 1, 1, true, 4, 
      2, 'movement.organicMatterChangeFromMineralization_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicNActiveHumusAdsorbedToSediment_kgPha',
      'N as active organic lost in eroded soil today',
      5573, 1, 1, true, 4, 
      2, 'movement.organicNActiveHumusAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicNFreshAddedFromDeadPlant_kgPha',
      'N as fresh organic in flat residue newly decayed from organic matter blobs today',
      5574, 1, 1, true, 4, 
      2, 'movement.organicNFreshAddedFromDeadPlant_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicNFreshAdsorbedToSediment_kgPha',
      'N as fresh organic in flat residue lost in eroded soil today',
      5575, 1, 1, true, 4, 
      2, 'movement.organicNFreshAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicNFreshFromOM_kgPha',
      'N as fresh organic in undecayed dead plant matter (in organic matter blobs) on t',
      5576, 1, 1, true, 4, 
      2, 'movement.organicNFreshFromOM_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicNStableHumusAdsorbedToSediment_kgPha',
      'N as stable organic in humus lost in eroded soil today',
      5577, 1, 1, true, 4, 
      2, 'movement.organicNStableHumusAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicPFreshAddedFromDeadPlant_kgPha',
      'P as fresh organic in flat residue newly decayed from organic matter blobs today',
      5578, 1, 1, true, 4, 
      2, 'movement.organicPFreshAddedFromDeadPlant_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicPFreshAdsorbedToSediment_kgPha',
      'P as fresh organic in flat residue lost in eroded soil today',
      5579, 1, 1, true, 4, 
      2, 'movement.organicPFreshAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicPFreshFromOM_kgPha',
      'P as fresh organic in undecayed dead plant matter (in organic matter blobs) on t',
      5580, 1, 1, true, 4, 
      2, 'movement.organicPFreshFromOM_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOrganicPHumusAdsorbedToSediment_kgPha',
      'P as organic in humus lost in eroded soil today',
      5581, 1, 1, true, 4, 
      2, 'movement.organicPHumusAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPatchIrrigationForDay_mm',
      'Patch irrigation today',
      5582, 1, 1, true, 4, 
      1, 'water.patchIrrigationForDay_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPatchRainfallForDay_mm',
      'Patch rainfall and snowmelt today',
      5583, 1, 1, true, 4, 
      1, 'water.patchRainfallForDay_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPatchTotalAboveGroundBiomassAndResidue_tPha',
      'Patch total above-ground biomass and residue today',
      5584, 1, 1, true, 4, 
      2, 'totals.patchTotalAboveGroundBiomassAndResidue_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPeakRainfallRate_mmPhr',
      'Rainfall rate at peak today',
      5585, 1, 1, true, 4, 
      1, 'water.peakRainfallRate_mmPhr', false);
  aspect.addUnitsAndBounds(0, 13, 2, 2, 5, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPeakRateEstimationMethod',
      'Method for estimating peak runoff rate',
      5586, 11, 1, false, 1, 
      1, 'params.peakRateEstimationMethod', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPeakRunoffRainfallEnergyAdjFactor',
      'Adjustment factor for peak runoff rate',
      5587, 1, 1, false, 1, 
      1, 'params.peakRunoffRainfallEnergyAdjFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.5, 2.0, 0.5, 2.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPeakRunoffRate_mmPhr',
      'Peak runoff rate from rainfall today',
      5588, 1, 1, true, 4, 
      1, 'water.peakRunoffRate_mmPhr', false);
  aspect.addUnitsAndBounds(0, 13, 2, 2, 5, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPFertAutoApplied_kgPha',
      'P fertilizer applied today',
      5589, 1, 1, true, 4, 
      2, 'movement.pFertAutoApplied_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPlowDepth_m',
      'Plow depth',
      5590, 1, 1, true, 4, 
      1, 'state.plowDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPlowDepthSWmWP_mm',
      'Water content minus wilting point in plow depth (0.2 m)',
      5591, 1, 1, true, 4, 
      1, 'totals.plowDepthSWmWP_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchPotEvapMethod',
      'Method for estimating potential evaporation',
      5592, 11, 1, false, 1, 
      1, 'params.potEvapMethod', true);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRainfallDuration_hr',
      'Rainfall duration today',
      5593, 1, 1, true, 4, 
      1, 'water.rainfallDuration_hr', false);
  aspect.addUnitsAndBounds(0, 24, 1, 1, 1, 0.0, 24.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRainfallEnergyFactorForUSLE',
      'Rainfall energy factor for USLE water erosion equation today',
      5594, 1, 1, true, 4, 
      1, 'erosion.rainfallEnergyFactorForUSLE', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRandomRoughness_mm',
      'Surface random roughness',
      5595, 1, 1, false, 2, 
      1, 'surface.randomRoughness_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRetentionParam_mm',
      'Retention parameter today',
      5596, 1, 1, true, 4, 
      1, 'water.retentionParam_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchReturnFlowTravelTime_days',
      'Time for sub-surface water to flow from watershed edge to center',
      5597, 1, 1, false, 1, 
      1, 'params.paramForReturnFlowTravelTime_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 2000.0, 0.0, 2000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRidgeHeight_mm',
      'Surface ridge height',
      5598, 1, 1, false, 2, 
      1, 'surface.ridgeHeight_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRidgeInterval_m',
      'Surface ridge interval',
      5599, 1, 1, false, 2, 
      1, 'surface.ridgeInterval_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchRunoffVolume_mm',
      'Runoff volume from rainfall today',
      5600, 1, 1, true, 4, 
      1, 'water.runoffVolume_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSnowfallForDay_mm',
      'Patch snowfall today',
      5601, 1, 1, true, 4, 
      1, 'water.snowfallForDay_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSnowmeltForDay_mm',
      'Patch snowmelt today',
      5602, 1, 1, true, 4, 
      1, 'water.snowmeltForDay_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSnowPackTemp_degC',
      'Snow pack temperature today',
      5603, 1, 1, true, 4, 
      1, 'water.snowPackTemp_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 40.0, -1000000.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSnowWaterContent_mm',
      'Snow water content for patch',
      5604, 1, 1, false, 2, 
      1, 'water.snowWaterContent_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilAlbedo_frn',
      'Bare-soil albedo',
      5605, 1, 1, false, 1, 
      1, 'params.soilAlbedo_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.05, 0.2, 0.05, 0.2, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilCoverIndex_frn',
      'Soil cover index today',
      5606, 1, 1, true, 4, 
      1, 'surface.soilCoverIndex_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilEvapByDepthCoeffs',
      'S Curve - effect of soil depth on soil evaporation',
      5607, 1, 4, false, 1, 
      3, 'params.soilEvapByDepthCoeffs', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilInsulationFromAirTempCoeffs',
      'S Curve - effect of plant cover on soil insulation from air temperature',
      5608, 1, 4, false, 1, 
      3, 'params.soilInsulationFromAirTempCoeffs', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 6.0, 0.0, 6.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilParticleDiameter_microns',
      'Soil particle diameter',
      5609, 1, 1, false, 1, 
      1, 'params.soilParticleDiameter_microns', false);
  aspect.addUnitsAndBounds(0, 2, 1, 2, 6, 300.0, 600.0, 300.0, 600.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilProfileDepth_m',
      'Soil profile depth',
      5610, 1, 1, true, 4, 
      1, 'state.soilProfileDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilProfileDepthFCmWP_mm',
      'Field capacity minus wilting point in soil profile depth',
      5611, 1, 1, true, 4, 
      1, 'totals.soilProfileDepthFCmWP_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilProfileDepthSWmWP_mm',
      'Water content minus wilting point in soil profile depth (2 m)',
      5612, 1, 1, true, 4, 
      1, 'totals.soilProfileDepthSWmWP_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilSettlingFromRainfallCoeffs',
      'S Curve - effect of rainfall amount on degree of soil settling',
      5613, 1, 4, false, 1, 
      3, 'params.soilSettlingFromRainfallCoeffs', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 200.0, 0.0, 200.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilSurfaceCoverLagFactor_frn',
      'Soil cover lag factor for surface temperature today',
      5614, 1, 1, true, 4, 
      1, 'movement.soilSurfaceCoverLagFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilSurfaceTempBare_degC',
      'Bare soil surface temperature today',
      5615, 1, 1, true, 4, 
      1, 'movement.soilSurfaceTempBare_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 40.0, -1000000.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilSurfaceTempWithCover_degC',
      'Covered soil surface temperature today',
      5616, 1, 1, true, 4, 
      1, 'movement.soilSurfaceTempWithCover_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 40.0, -1000000.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchSoilWeatheringType',
      'Soil weathering type',
      5617, 11, 1, false, 1, 
      1, 'params.soilWeatheringType', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTemp_degC',
      'Temperature at soil surface today',
      5618, 1, 1, true, 4, 
      1, 'surface.temp_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 40.0, -1000000.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchThicknessWaitingToBeEroded_m',
      'Thickness waiting to be eroded today',
      5619, 1, 1, false, 4, 
      1, 'erosion.thicknessWaitingToBeEroded_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 1.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTimeForDrainageSystemToReducePlantStress_days',
      'Time for drainage system to reduce water stress',
      5620, 1, 1, false, 1, 
      1, 'params.timeForDrainageSystemToReducePlantStress_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTimeOfConc_hr',
      'Rainfall time of concentration today',
      5621, 1, 1, true, 4, 
      1, 'water.timeOfConc_hr', false);
  aspect.addUnitsAndBounds(0, 24, 1, 1, 1, 0.0, 24.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTop1mPorosity_mm',
      'Porosity in top meter of soil',
      5622, 1, 1, true, 4, 
      1, 'totals.top1mPorosity_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTop1MWaterContent_mm',
      'Water content in top meter of soil',
      5623, 1, 1, true, 4, 
      1, 'totals.top1MWaterContent_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTop30cmFractionFieldCapacity_frn',
      'Fraction of field capacity in top 30 cm',
      5624, 1, 1, true, 4, 
      1, 'totals.top30cmFractionFieldCapacity_frn', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalErosion_tPha',
      'Water erosion today',
      5625, 1, 1, true, 4, 
      2, 'erosion.totalErosion_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalNInStandingDead_kgPha',
      'N total in above-ground dead biomass for plants in patch today',
      5626, 1, 1, true, 4, 
      2, 'plantMeans.totalNInStandingDead_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalNUptakeByPlants_kgPha',
      'N total uptake by plants today',
      5627, 1, 1, true, 4, 
      2, 'movement.totalNUptakeByPlants_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalPInStandingDead_kgPha',
      'P total in above-ground dead biomass for plants in patch today',
      5628, 1, 1, true, 4, 
      2, 'plantMeans.totalPInStandingDead_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalPUptakeByPlants_kgPha',
      'P total uptake by plants today',
      5629, 1, 1, true, 4, 
      2, 'movement.totalPUptakeByPlants_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalStandingDead_tPha',
      'Total above-ground dead biomass of plants in patch today',
      5630, 1, 1, true, 4, 
      2, 'plantMeans.totalStandingDead_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalStandingLive_tPha',
      'Total above-ground live biomass of plants in patch today',
      5631, 1, 1, true, 4, 
      2, 'plantMeans.totalStandingLive_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchTotalWaterUse_mm',
      'Total water use for plants in patch today',
      5632, 1, 1, true, 4, 
      2, 'plantMeans.totalWaterUse_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchUserCoeffsForMUSI',
      'Coefficients for MUSI water erosion equation',
      5633, 1, 9, false, 1, 
      1, 'params.userCoeffsForMUSI[index]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.1, 5.0, 0.0, 5.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchUseStochasticCurveNumberEstimation',
      'Vary curve numbers randomly',
      5634, 8, 1, false, 1, 
      1, 'params.useStochasticCurveNumberEstimation', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterErosion_tPha',
      'Water erosion from rainfall today',
      5635, 1, 1, true, 4, 
      2, 'erosion.waterErosion_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterErosionMethod',
      'Method for estimating water erosion',
      5636, 11, 1, false, 1, 
      1, 'params.waterErosionMethod', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterReturnFlowTravelTime_days',
      'Travel time for return flow today',
      5637, 1, 1, true, 4, 
      1, 'water.returnFlowTravelTime_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 2000.0, 0.0, 2000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedArea_ha',
      'Watershed area for water flow',
      5638, 1, 1, false, 1, 
      1, 'params.watershedArea_ha', false);
  aspect.addUnitsAndBounds(0, 8, 1, 1, 7, 0.1, 10.0, 0.00001, 100.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedChannelDepth_m',
      'Watershed channel depth for water flow',
      5639, 1, 1, false, 1, 
      1, 'params.watershedChannelDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.01, 5.0, 0.01, 5.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedChannelLength_km',
      'Watershed channel length for water flow',
      5640, 1, 1, false, 1, 
      1, 'params.watershedChannelLength_km', false);
  aspect.addUnitsAndBounds(0, 2, 5, 4, 7, 0.0, 5.0, 0.0, 5.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedChannelSlope_mPm',
      'Watershed channel slope for water flow',
      5641, 1, 1, false, 1, 
      1, 'params.watershedChannelSlope_mPm', false);
  aspect.addUnitsAndBounds(0, 21, 1, 1, 1, 0.0, 4.0, 0.0, 4.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedFieldLength_km',
      'Field length for wind erosion',
      5642, 1, 1, false, 1, 
      1, 'params.watershedFieldLength_km', false);
  aspect.addUnitsAndBounds(0, 2, 5, 4, 7, 0.0, 4.0, 0.0, 4.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedFieldLengthOrientationFromNorth_rad',
      'Field orientation (from due North) for wind erosion',
      5643, 1, 1, false, 1, 
      1, 'params.watershedFieldLengthOrientationFromNorth_rad', false);
  aspect.addUnitsAndBounds(0, 4, 1, 2, 2, 0.0, 6.28, 0.0, 6.28, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedFieldWidth_km',
      'Field width for wind erosion',
      5644, 1, 1, false, 1, 
      1, 'params.watershedFieldWidth_km', false);
  aspect.addUnitsAndBounds(0, 2, 5, 4, 7, 0.0, 2.0, 0.0, 2.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedSlopeLength_m',
      'Watershed slope length for water flow',
      5645, 1, 1, false, 1, 
      1, 'params.watershedSlopeLength_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 10.0, 150.0, 10.0, 150.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWatershedSlopeSteepness_mPm',
      'Watershed slope steepness for water flow',
      5646, 1, 1, false, 1, 
      1, 'params.watershedSlopeSteepness_mPm', false);
  aspect.addUnitsAndBounds(0, 21, 1, 1, 1, 0.0001, 0.5, 0.0001, 0.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterStressFactorForAutoIrr',
      'Water stress factor to trigger auto irrigation',
      5647, 1, 1, false, 1, 
      1, 'params.waterStressFactorForAutoIrr', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, -500.0, 1500.0, -500.0, 1500.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterTableDepth_m',
      'Water table depth',
      5648, 1, 1, false, 2, 
      1, 'water.waterTabledepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterTableMaxDepth_m',
      'Water table maximum depth',
      5649, 1, 1, false, 1, 
      1, 'params.waterTableMaxDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWaterTableMinDepth_m',
      'Water table minimum depth',
      5650, 1, 1, false, 1, 
      1, 'params.waterTableMinDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWindErosion_tPha',
      'Wind erosion today',
      5651, 1, 1, true, 4, 
      2, 'erosion.windErosion_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWindErosionAccelerationFactor',
      'Factor for accelerating wind erosion',
      5652, 1, 1, false, 1, 
      1, 'params.windErosionAccelerationFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1000.0, 0.0, 10.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWindErosionAccumCoeff',
      'Lag coefficient for wind erosion',
      5653, 1, 1, false, 1, 
      1, 'params.windErosionAccumCoeff', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.005, 0.1, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchWindErosionAccumulatedFactor',
      'Wind erosion accumulated factor today',
      5654, 1, 1, false, 4, 
      1, 'erosion.windErosionAccumulatedFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 100.0, 0.0, 10000.0, 0);
  aspectManager.addAspect(aspect);
    end;

end.
