unit uasp_s3;
{Copyright (c) 1997 Paul D. Fernhout and Cynthia F. Kurtz All rights reserved
http://www.gardenwithinsight.com. See the license file for details on redistribution.
=====================================================================================
DO NOT EDIT THIS FILE. It was generated by the tab2asp program from aspects.tab.
uasp_s3: Aspect creation for soil patch (part 3).}

interface

uses uaspects;

procedure SoilPatch_createAspects3(aspectManager: GsAspectManager);

implementation

procedure SoilPatch_createAspects3(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
    end;

end.
