unit uasp_dpl;
{Copyright (c) 1997 Paul D. Fernhout and Cynthia F. Kurtz All rights reserved
http://www.gardenwithinsight.com. See the license file for details on redistribution.
=====================================================================================
DO NOT EDIT THIS FILE. It was generated by the tab2asp program from aspects.tab.
uasp_dpl: Aspect creation for drawing plant.}

interface

uses uaspects;

procedure DrawingPlant_createAspects(aspectManager: GsAspectManager);

implementation

procedure DrawingPlant_createAspects(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
  aspect := GsAspect.createWithInfo('kPlantZZDrawAxillaryBudBackfaceColor',
      'Axillary bud back face color',
      5198, 7, 1, false, 1, 
      1, 'pAxillaryBud.BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawAxillaryBudFaceColor',
      'Axillary bud front face color',
      5199, 7, 1, false, 1, 
      1, 'pAxillaryBud.FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawAxillaryBudObject3D',
      'Axillary bud 3D object',
      5200, 10, 1, false, 1, 
      5, 'pAxillaryBud.object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawAxillaryBudScale',
      'Axillary bud 3D object scale at full size',
      5201, 1, 1, false, 1, 
      1, 'pAxillaryBud.Scale', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudFemaleBackfaceColor',
      'Female flower bud petal back face color',
      5202, 7, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BudBackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudFemaleFaceColor',
      'Female flower bud petal front face color',
      5203, 7, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BudFaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudMaleBackfaceColor',
      'Male flower bud petal back face color',
      5204, 7, 1, false, 1, 
      1, 'pFlower[kGenderMale].BudBackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudMaleFaceColor',
      'Male flower bud petal front face color',
      5205, 7, 1, false, 1, 
      1, 'pFlower[kGenderMale].BudFaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudNumPetalsFemale',
      'Female flower number of petals on bud',
      5206, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BudNumPetals', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 10.0, 1.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudNumPetalsMale',
      'Male flower number of petals on bud',
      5207, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].BudNumPetals', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 10.0, 1.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudPetalsAreRadiallyArrangedFemale',
      'Female flower bud petals are radially arranged',
      5208, 8, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BudPetalsAreRadiallyArranged', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudPetalsAreRadiallyArrangedMale',
      'Male flower bud petals are radially arranged',
      5209, 8, 1, false, 1, 
      1, 'pFlower[kGenderMale].BudPetalsAreRadiallyArranged', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudScaleAtFullSizeFemale',
      'Female flower bud 3D object scale at full size',
      5210, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BudScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 100.0, 0.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerBudScaleAtFullSizeMale',
      'Male flower bud 3D object scale at full size',
      5211, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].BudScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 100.0, 0.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerDaysBeforeDropFemale',
      'Female flower days until drop',
      5212, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].DaysBeforeDrop', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 365.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerDaysBeforeDropMale',
      'Male flower days until drop',
      5213, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].DaysBeforeDrop', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 365.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerFemaleBackfaceColor',
      'Female flower petal back face color',
      5214, 7, 1, false, 1, 
      1, 'pFlower[kGenderFemale].BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerFemaleBudObject3D',
      'Female flower bud 3D object',
      5215, 10, 1, false, 1, 
      5, 'pFlower[kGenderFemale].budObject3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerFemaleFaceColor',
      'Female flower petal front face color',
      5216, 7, 1, false, 1, 
      1, 'pFlower[kGenderFemale].FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerFemaleObject3D',
      'Female flower petal 3D object',
      5217, 10, 1, false, 1, 
      5, 'pFlower[kGenderFemale].object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaleBackfaceColor',
      'Male flower petal back face color',
      5218, 7, 1, false, 1, 
      1, 'pFlower[kGenderMale].BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaleBudObject3D',
      'Male flower bud 3D object',
      5219, 10, 1, false, 1, 
      5, 'pFlower[kGenderMale].budObject3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaleFaceColor',
      'Male flower petal front face color',
      5220, 7, 1, false, 1, 
      1, 'pFlower[kGenderMale].FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaleObject3D',
      'Male flower petal 3D object',
      5221, 10, 1, false, 1, 
      5, 'pFlower[kGenderMale].object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaxDaysToCreateFlowerBudIfOverMinFractFemale',
      'Female flower maximum days for inflorescence to create bud',
      5222, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MaxDaysToCreateFlowerBudIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaxDaysToCreateFlowerBudIfOverMinFractMale',
      'Male flower maximum days for inflorescence to create bud',
      5223, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].MaxDaysToCreateFlowerBudIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaxDaysToGrowIfOverMinFractionFemale',
      'Female flower maximum days to grow',
      5224, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MaxDaysToGrowIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMaxDaysToGrowIfOverMinFractionMale',
      'Male flower maximum days to grow',
      5225, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].MaxDaysToGrowIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinDaysToCreateFlowerBudFemale',
      'Female flower minimum days for inflorescence to create bud',
      5226, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MinDaysToCreateFlowerBud', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinDaysToCreateFlowerBudMale',
      'Male flower minimum days for inflorescence to create bud',
      5227, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].MinDaysToCreateFlowerBud', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinDaysToGrowFemale',
      'Female flower minimum days to grow',
      5228, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MinDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinDaysToGrowMale',
      'Male flower minimum days to grow',
      5229, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].MinDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractOptBiomassToOpenFlowerFemale',
      'Female flower minimum fraction of optimal biomass needed to open',
      5230, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MinFractionOfOptimalBiomassToOpenFlower_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractionOfOptimalBiomassToCreateFruitFemale',
      'Female flower minimum fraction of optimal biomass needed to set fruit',
      5231, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].minFractionOfOptimalBiomassToCreateFruit_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractOptBiomassToOpenFlowerMale',
      'Male flower minimum fraction of optimal biomass needed to open',
      5232, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].MinFractionOfOptimalBiomassToOpenFlower_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractionOfOptimalBiomassToCreateFruitMale',
      'Male flower minimum fraction of optimal biomass needed to set fruit',
      5233, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].minFractionOfOptimalBiomassToCreateFruit_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractOptInitBiomassToCreateFlowerFemale',
      'Female flower minimum fraction of optimal biomass needed to create',
      5234, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].MinFractionOfOptimalInitialBiomassToCreateFlower_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerMinFractOptInitBiomassToCreateFlowerMale',
      'Male flower minimum fraction of optimal biomass needed to create',
      5235, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].MinFractionOfOptimalInitialBiomassToCreateFlower_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerNumPetalsFemale',
      'Female flower number of petals',
      5236, 2, 1, false, 1, 
      1, 'pFlower[kGenderFemale].NumPetals', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerNumPetalsMale',
      'Male flower number of petals',
      5237, 2, 1, false, 1, 
      1, 'pFlower[kGenderMale].NumPetals', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerOptimalBiomassFemale',
      'Female flower optimal biomass',
      5238, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].OptimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerOptimalBiomassMale',
      'Male flower optimal biomass',
      5239, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].OptimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerPetalsAreRadiallyArrangedFemale',
      'Female flower petals are radially arranged',
      5240, 8, 1, false, 1, 
      1, 'pFlower[kGenderFemale].PetalsAreRadiallyArranged', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerPetalsAreRadiallyArrangedMale',
      'Male flower petals are radially arranged',
      5241, 8, 1, false, 1, 
      1, 'pFlower[kGenderMale].PetalsAreRadiallyArranged', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerScaleAtFullSizeFemale',
      'Female flower petal 3D object scale at full size',
      5242, 1, 1, false, 1, 
      1, 'pFlower[kGenderFemale].ScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFlowerScaleAtFullSizeMale',
      'Male flower petal 3D object scale at full size',
      5243, 1, 1, false, 1, 
      1, 'pFlower[kGenderMale].ScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitDaysToRipen',
      'Fruit days to ripen once full-sized',
      5244, 2, 1, false, 1, 
      1, 'pFruit.DaysToRipen', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitMaxDaysToGrow',
      'Fruit maximum days to grow',
      5245, 2, 1, false, 1, 
      1, 'pFruit.MaxDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitMinDaysToGrow',
      'Fruit minimum days to grow',
      5246, 2, 1, false, 1, 
      1, 'pFruit.MinDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitNumSections',
      'Fruit number of section 3D objects',
      5247, 2, 1, false, 1, 
      1, 'pFruit.NumSections', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitObject3D',
      'Fruit section 3D object',
      5248, 10, 1, false, 1, 
      5, 'pFruit.object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitOptimumMass_kg',
      'Fruit optimum biomass',
      5249, 1, 1, false, 1, 
      1, 'pFruit.optimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitRipeBackfaceColor',
      'Fruit ripe section back face color',
      5250, 7, 1, false, 1, 
      1, 'pFruit.RipeBackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitRipeFaceColor',
      'Fruit ripe section front face color',
      5251, 7, 1, false, 1, 
      1, 'pFruit.RipeFaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitScaleAtFullSize',
      'Fruit section 3D object scale at full size',
      5252, 1, 1, false, 1, 
      1, 'pFruit.ScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitSCurve',
      'S curve - effect of fruit age on fruit optimal biomass',
      5253, 1, 4, false, 1, 
      3, 'pFruit.sCurveParams', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitSectionsAreRadiallyArranged',
      'Fruit sections are radially arranged',
      5254, 8, 1, false, 1, 
      1, 'pFruit.SectionsAreRadiallyArranged', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitStalkStrengthIndex',
      'Fruit stalk strength index',
      5255, 1, 1, false, 1, 
      1, 'pFruit.StalkStrengthIndex', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitUnripeBackfaceColor',
      'Fruit unripe section back face color',
      5256, 7, 1, false, 1, 
      1, 'pFruit.UnripeBackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawFruitUnripeFaceColor',
      'Fruit unripe section front face color',
      5257, 7, 1, false, 1, 
      1, 'pFruit.UnripeFaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralGender',
      'Plant gender',
      5258, 11, 1, false, 1, 
      1, 'pGeneral.Gender', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralHarvestItemsBundledWithWholePlant',
      'Harvest items bundled with whole plant',
      5259, 11, 1, false, 1, 
      7, '(not needed)', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralIsDicot',
      'Plant is dicotyledonous (has two seedling leaves)',
      5260, 8, 1, false, 1, 
      1, 'pGeneral.IsDicot', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralLineDivisions',
      'Plant number of segments to draw to create curved line',
      5261, 2, 1, false, 1, 
      1, 'pGeneral.LineDivisions', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 10.0, 1.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralMaleFlowersAreSeparate',
      'Plant has both male and female flowers',
      5262, 8, 1, false, 1, 
      1, 'pGeneral.MaleFlowersAreSeparate', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralNumApicalInflors',
      'Plant number of apical (terminal) inflorescences',
      5263, 2, 1, false, 1, 
      1, 'pGeneral.NumApicalInflors', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralNumAxillaryInflors',
      'Plant number of axillary inflorescences',
      5264, 2, 1, false, 1, 
      1, 'pGeneral.NumAxillaryInflors', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralRandomSway',
      'Plant random sway in drawing angles',
      5265, 1, 1, false, 1, 
      1, 'pGeneral.randomSway', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawGeneralStorageOrganLumpedWith',
      'Lump storage organ in with',
      5266, 11, 1, false, 1, 
      6, '(not needed)', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateAxillaryBud',
      'Harvest display item for axillary bud',
      5267, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeAxillaryBud]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateFemaleFlower',
      'Harvest display item for female flower',
      5268, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeFemaleFlower]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateFemaleFlowerBud',
      'Harvest display item for female flower bud',
      5269, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeFemaleFlowerBud]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateFemaleInflorescence',
      'Harvest display item for female inflorescence',
      5270, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeFemaleInflorescence]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateFruit',
      'Harvest display item for fruit',
      5271, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeFruit]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateLeaf',
      'Harvest display item for leaf',
      5272, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeLeaf]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateMaleFlower',
      'Harvest display item for male flower',
      5273, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeMaleFlower]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateMaleFlowerBud',
      'Harvest display item for male flower bud',
      5274, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeMaleFlowerBud]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateMaleInflorescence',
      'Harvest display item for male inflorescence',
      5275, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeMaleInflorescence]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateRoot',
      'Harvest display item for root',
      5276, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeRoot]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateSeedlingLeaf',
      'Harvest display item for seedling leaf',
      5277, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeSeedlingLeaf]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateStem',
      'Harvest display item for stem (internode)',
      5278, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeStem]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateStorageOrgan',
      'Harvest display item for storage organ',
      5279, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeStorageOrgan]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawHarvestItemTemplateWholePlant',
      'Harvest display item for whole plant',
      5280, 12, 1, false, 1, 
      4, 'pGeneral.harvestItemTemplatesArray[kHarvestPartTypeWholePlant]', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBiomassRequiredFemale',
      'Female inflorescence optimal biomass',
      5281, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].optimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBiomassRequiredMale',
      'Male inflorescence optimal biomass',
      5282, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].optimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBranchAngleFemale',
      'Female inflorescence angle of branch with main stem',
      5283, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].BranchAngle', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBranchAngleMale',
      'Male inflorescence angle of branch with main stem',
      5284, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].BranchAngle', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBranchesAreAlternateFemale',
      'Female inflorescence branches are alternate',
      5285, 8, 1, false, 1, 
      1, 'pInflor[kGenderFemale].BranchesAreAlternate', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceBranchesAreAlternateMale',
      'Male inflorescence branches are alternate',
      5286, 8, 1, false, 1, 
      1, 'pInflor[kGenderMale].BranchesAreAlternate', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceDaysToAllFlowersShowingFemale',
      'Female inflorescence days for all flowers to develop',
      5287, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].daysToAllFlowersCreated', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceDaysToAllFlowersShowingMale',
      'Male inflorescence days for all flowers to develop',
      5288, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].daysToAllFlowersCreated', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceFemaleStalkColor',
      'Female inflorescence stalk color',
      5289, 7, 1, false, 1, 
      1, 'pInflor[kGenderFemale].StalkColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceFlowersDrawTopToBottomFemale',
      'Female inflorescence flowers develop from top to bottom',
      5290, 8, 1, false, 1, 
      1, 'pInflor[kGenderFemale].FlowersDrawTopToBottom', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceFlowersDrawTopToBottomMale',
      'Male inflorescence flowers develop from top to bottom',
      5291, 8, 1, false, 1, 
      1, 'pInflor[kGenderMale].FlowersDrawTopToBottom', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceFlowersSpiralOnStemFemale',
      'Female inflorescence flowers spiral around main stem',
      5292, 8, 1, false, 1, 
      1, 'pInflor[kGenderFemale].FlowersSpiralOnStem', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceFlowersSpiralOnStemMale',
      'Male inflorescence flowers spiral around main stem',
      5293, 8, 1, false, 1, 
      1, 'pInflor[kGenderMale].FlowersSpiralOnStem', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceInternodeLengthFemale',
      'Female inflorescence internode length (between flowers)',
      5294, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].InternodeLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceInternodeLengthMale',
      'Male inflorescence internode length (between flowers)',
      5295, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].InternodeLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceInternodeWidthFemale',
      'Female inflorescence stem width',
      5296, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].InternodeWidth_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceInternodeWidthMale',
      'Male inflorescence stem width',
      5297, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].InternodeWidth_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceIsHeadFemale',
      'Female inflorescence is head type (like sunflower)',
      5298, 8, 1, false, 1, 
      1, 'pInflor[kGenderFemale].IsHead', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceIsHeadMale',
      'Male inflorescence is head type (like sunflower)',
      5299, 8, 1, false, 1, 
      1, 'pInflor[kGenderMale].IsHead', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceIsTerminalFemale',
      'Female inflorescence is apical',
      5300, 8, 1, false, 1, 
      1, 'pInflor[kGenderFemale].IsTerminal', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceIsTerminalMale',
      'Male inflorescence is apical',
      5301, 8, 1, false, 1, 
      1, 'pInflor[kGenderMale].IsTerminal', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMaleStalkColor',
      'Male inflorescence stalk color',
      5302, 7, 1, false, 1, 
      1, 'pInflor[kGenderMale].StalkColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMaxDaysToCreateIfOverMinFractFemale',
      'Female inflorescence maximum days for meristem to create',
      5303, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MaxDaysToCreateInflorescenceIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMaxDaysToCreateIfOverMinFractMale',
      'Male inflorescence maximum days for meristem to create',
      5304, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].MaxDaysToCreateInflorescenceIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMaxDaysToGrowFemale',
      'Female inflorescence maximum days to grow',
      5305, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MaxDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMaxDaysToGrowMale',
      'Male inflorescence maximum days to grow',
      5306, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].MaxDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinDaysToCreateInflorescenceFemale',
      'Female inflorescence minimum days for meristem to create',
      5307, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MinDaysToCreateInflorescence', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinDaysToCreateInflorescenceMale',
      'Male inflorescence minimum days for meristem to create',
      5308, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].MinDaysToCreateInflorescence', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinDaysToGrowFemale',
      'Female inflorescence minimum days to grow',
      5309, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MinDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinDaysToGrowMale',
      'Male inflorescence minimum days to grow',
      5310, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].MinDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinFractOptBiomassForFlowersFemale',
      'Female inflorescence minimum fraction of optimal biomass needed to make flowers',
      5311, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MinFractionOfOptimalBiomassToMakeFlowers_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinFractOptBiomassForFlowersMale',
      'Male inflorescence minimum fraction of optimal biomass needed to make flowers',
      5312, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].MinFractionOfOptimalBiomassToMakeFlowers_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinFractOptBiomassToCreateFemale',
      'Female inflorescence minimum fraction of optimal biomass needed to create',
      5313, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].MinFractionOfOptimalBiomassToCreateInflorescence_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceMinFractOptBiomassToCreateMale',
      'Male inflorescence minimum fraction of optimal biomass needed to create',
      5314, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].MinFractionOfOptimalBiomassToCreateInflorescence_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceNumBranchesFemale',
      'Female inflorescence number of branches',
      5315, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].NumBranches', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceNumBranchesMale',
      'Male inflorescence number of branches',
      5316, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].NumBranches', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceNumFlowersFemale',
      'Female inflorescence number of flowers',
      5317, 2, 1, false, 1, 
      1, 'pInflor[kGenderFemale].NumFlowers', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceNumFlowersMale',
      'Male inflorescence number of flowers',
      5318, 2, 1, false, 1, 
      1, 'pInflor[kGenderMale].NumFlowers', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 30.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePedicelAngleFemale',
      'Female inflorescence angle of pedicel with main stem',
      5319, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].PedicelAngle', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePedicelAngleMale',
      'Male inflorescence angle of pedicel with main stem',
      5320, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].PedicelAngle', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePedicelLengthFemale',
      'Female inflorescence pedicel (flower stalk) length',
      5321, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].PedicelLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePedicelLengthMale',
      'Male inflorescence pedicel (flower stalk) length',
      5322, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].PedicelLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePeduncleLengthFemale',
      'Female inflorescence peduncle (primary stalk) length',
      5323, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].PeduncleLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescencePeduncleLengthMale',
      'Male inflorescence peduncle (primary stalk) length',
      5324, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].PeduncleLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceTerminalStalkLengthFemale',
      'Female inflorescence apical stalk length',
      5325, 1, 1, false, 1, 
      1, 'pInflor[kGenderFemale].TerminalStalkLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInflorescenceTerminalStalkLengthMale',
      'Male inflorescence apical stalk length',
      5326, 1, 1, false, 1, 
      1, 'pInflor[kGenderMale].TerminalStalkLength_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeBackfaceColor',
      'Internode back face color',
      5327, 7, 1, false, 1, 
      1, 'pInternode.BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeBoltingMaxDaysToBolt',
      'Internode maximum days to bolt',
      5328, 2, 1, false, 1, 
      1, 'pInternode.MaxDaysToBolt', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeBoltingMinDaysToBolt',
      'Internode minimum days to bolt',
      5329, 2, 1, false, 1, 
      1, 'pInternode.MinDaysToBolt', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeCanRecoverFromStuntingDuringCreation',
      'Internode can recover from stunting at creation',
      5330, 8, 1, false, 1, 
      1, 'pInternode.CanRecoverFromStuntingDuringCreation', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeFaceColor',
      'Internode front face color',
      5331, 7, 1, false, 1, 
      1, 'pInternode.FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeFlexibilityIndex',
      'Internode flexibility index',
      5332, 1, 1, false, 1, 
      1, 'pInternode.FlexibilityIndex', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeLengthAtOptimalFinalBiomassAndExpansion_mm',
      'Internode length at optimal biomass and full expansion',
      5333, 1, 1, false, 1, 
      1, 'pInternode.LengthAtOptimalFinalBiomassAndExpansion_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 1.0, 100.0, 1.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeLengthMultiplierDueToBiomassAccretion',
      'Internode length increase due to biomass increase, multiplier',
      5334, 1, 1, false, 1, 
      1, 'pInternode.LengthMultiplierDueToBiomassAccretion', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeLengthMultiplierDueToBolting',
      'Internode length increase due to bolting, multiplier',
      5335, 1, 1, false, 1, 
      1, 'pInternode.LengthMultiplierDueToBolting', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeLengthMultiplierDueToExpansion',
      'Internode length increase due to water uptake, multiplier',
      5336, 1, 1, false, 1, 
      1, 'pInternode.LengthMultiplierDueToExpansion', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMaxDaysToAccumulateBiomass',
      'Internode maximum days to grow',
      5337, 2, 1, false, 1, 
      1, 'pInternode.MaxDaysToAccumulateBiomass', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMaxDaysToCreateInternodeIfOverMinFraction',
      'Internode maximum days for meristem to create',
      5338, 2, 1, false, 1, 
      1, 'pInternode.MaxDaysToCreateInternodeIfOverMinFraction', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMaxDaysToExpand',
      'Internode maximum days to expand by water uptake',
      5339, 2, 1, false, 1, 
      1, 'pInternode.MaxDaysToExpand', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMeanderIndex',
      'Internode curving index',
      5340, 1, 1, false, 1, 
      1, 'pInternode.MeanderIndex', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMinDaysToAccumulateBiomass',
      'Internode minimum days to grow',
      5341, 2, 1, false, 1, 
      1, 'pInternode.MinDaysToAccumulateBiomass', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMinDaysToCreateInternode',
      'Internode minimum days for meristem to create',
      5342, 2, 1, false, 1, 
      1, 'pInternode.MinDaysToCreateInternode', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMinDaysToExpand',
      'Internode minimum days to expand by water uptake',
      5343, 2, 1, false, 1, 
      1, 'pInternode.MinDaysToExpand', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeMinFractionOfOptimalInitialBiomassToCreateInternode_frn',
      'Internode minimum fraction of optimal biomass needed to create',
      5344, 1, 1, false, 1, 
      1, 'pInternode.MinFractionOfOptimalInitialBiomassToCreateInternode_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeOptimalFinalBiomass_kg',
      'Internode optimal final biomass',
      5345, 1, 1, false, 1, 
      1, 'pInternode.OptimalFinalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeWidthAtOptimalFinalBiomassAndExpansion_mm',
      'Internode width at optimal biomass and expansion',
      5346, 1, 1, false, 1, 
      1, 'pInternode.WidthAtOptimalFinalBiomassAndExpansion_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 1.0, 10.0, 1.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeWidthMultiplierDueToBiomassAccretion',
      'Internode width increase by biomass increase, multiplier',
      5347, 1, 1, false, 1, 
      1, 'pInternode.WidthMultiplierDueToBiomassAccretion', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawInternodeWidthMultiplierDueToExpansion',
      'Internode width increase by water uptake, multiplier',
      5348, 1, 1, false, 1, 
      1, 'pInternode.WidthMultiplierDueToExpansion', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafBackfaceColor',
      'Leaf back face color',
      5349, 7, 1, false, 1, 
      1, 'pLeaf.BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafCompoundNumLeaflets',
      'Leaf compound number of leaflets',
      5350, 2, 1, false, 1, 
      1, 'pLeaf.CompoundNumLeaflets', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 20.0, 1.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafCompoundPetioleToRachisRatio',
      'Leaf compound ratio of petiole to rachis internode',
      5351, 1, 1, false, 1, 
      1, 'pLeaf.CompoundPetioleToRachisRatio', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafCompoundPinnateOrPalmate',
      'Leaf compound palmate',
      5352, 11, 1, false, 1, 
      1, 'pLeaf.CompoundPinnateOrPalmate', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafFaceColor',
      'Leaf front face color',
      5353, 7, 1, false, 1, 
      1, 'pLeaf.FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafFractionOfLiveBiomassWhenAbscisses_frn',
      'Leaf fraction of biomass is alive when falls off (abscisses)',
      5354, 1, 1, false, 1, 
      1, 'pLeaf.fractionOfLiveBiomassWhenAbscisses_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafMaxDaysToGrow',
      'Leaf maximum days to grow',
      5355, 2, 1, false, 1, 
      1, 'pLeaf.MaxDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafMinDaysToGrow',
      'Leaf minimum days to grow',
      5356, 2, 1, false, 1, 
      1, 'pLeaf.minDaysToGrow', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 1.0, 100.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafObject3D',
      'Leaf 3D object',
      5357, 10, 1, false, 1, 
      5, 'pLeaf.object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafOptimalBiomass_kg',
      'Leaf optimal biomass',
      5358, 1, 1, false, 1, 
      1, 'pLeaf.optimalBiomass_kg', false);
  aspect.addUnitsAndBounds(0, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafOptimalFractionOfOptimalBiomassAtCreation_frn',
      'Leaf fraction of optimal final biomass at creation',
      5359, 1, 1, false, 1, 
      1, 'pLeaf.optimalFractionOfOptimalBiomassAtCreation_kg', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafPetioleAngle',
      'Leaf angle between stem and petiole',
      5360, 1, 1, false, 1, 
      1, 'pLeaf.PetioleAngle', false);
  aspect.addUnitsAndBounds(0, 4, 2, 2, 2, 0.0, 180.0, 0.0, 360.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafPetioleColor',
      'Leaf petiole color',
      5361, 7, 1, false, 1, 
      1, 'pLeaf.PetioleColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafPetioleLengthAtOptimalBiomass_mm',
      'Leaf petiole length when leaf has optimal biomass',
      5362, 1, 1, false, 1, 
      1, 'pLeaf.PetioleLengthAtOptimalBiomass_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafPetioleWidthAtOptimalBiomass_mm',
      'Leaf petiole width when leaf has optimal biomass',
      5363, 1, 1, false, 1, 
      1, 'pLeaf.PetioleWidthAtOptimalBiomass_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawLeafScaleAtOptimalBiomass',
      'Leaf 3D object scale at optimal leaf biomass',
      5364, 1, 1, false, 1, 
      1, 'pLeaf.ScaleAtOptimalBiomass', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawMeristemBranchingDistance',
      'Meristem strength of apical dominance (as node distance)',
      5365, 1, 1, false, 1, 
      1, 'pMeristem.BranchingDistance', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawMeristemBranchingIndex',
      'Meristem axillary branching index',
      5366, 1, 1, false, 1, 
      1, 'pMeristem.BranchingIndex', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawMeristemBranchingIsAlternate',
      'Leaves and axillary meristems are alternate',
      5367, 8, 1, false, 1, 
      1, 'pMeristem.BranchingIsAlternate', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawMeristemBranchingIsSympodial',
      'Meristem branching is sympodial',
      5368, 8, 1, false, 1, 
      1, 'pMeristem.BranchingIsSympodial', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawMeristemDeterminateProbability',
      'Meristem probability to become reproductive when get flowering signal',
      5369, 1, 1, false, 1, 
      1, 'pMeristem.DeterminateProbability', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawRootTopBackfaceColor',
      'Root top back face color',
      5370, 7, 1, false, 1, 
      1, 'pRoot.BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawRootTopFaceColor',
      'Root top front face color',
      5371, 7, 1, false, 1, 
      1, 'pRoot.FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawRootTopObject3D',
      'Root top 3D object',
      5372, 10, 1, false, 1, 
      5, 'pRoot.object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawRootTopScaleAtFullSize',
      'Root top 3D object scale at full size',
      5373, 1, 1, false, 1, 
      1, 'pRoot.ScaleAtFullSize', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawRootTopShowsAboveGround',
      'Root top shows above ground',
      5374, 8, 1, false, 1, 
      1, 'pRoot.ShowsAboveGround', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawSeedlingLeafBackfaceColor',
      'Seedling leaf back face color',
      5375, 7, 1, false, 1, 
      1, 'pSeedlingLeaf.BackfaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawSeedlingLeafFaceColor',
      'Seedling leaf front face color',
      5376, 7, 1, false, 1, 
      1, 'pSeedlingLeaf.FaceColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawSeedlingLeafNodesOnStemWhenFallsOff',
      'Seedling leaf number of nodes on main stem when falls off',
      5377, 2, 1, false, 1, 
      1, 'pSeedlingLeaf.NodesOnStemWhenFallsOff', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 20.0, 1.0, 1000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawSeedlingLeafObject3D',
      'Seedling leaf 3D object',
      5378, 10, 1, false, 1, 
      5, 'pSeedlingLeaf.object3D', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantZZDrawSeedlingLeafScale',
      'Seedling leaf 3D object scale',
      5379, 1, 1, false, 1, 
      1, 'pSeedlingLeaf.Scale', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
    end;

end.
