unit uasp_pla;
{Copyright (c) 1997 Paul D. Fernhout and Cynthia F. Kurtz All rights reserved
http://www.gardenwithinsight.com. See the license file for details on redistribution.
=====================================================================================
DO NOT EDIT THIS FILE. It was generated by the tab2asp program from aspects.tab.
uasp_pla: Aspect creation for plant.}

interface

uses uaspects;

procedure Plant_createAspects1(aspectManager: GsAspectManager);
procedure Plant_createAspects2(aspectManager: GsAspectManager);

implementation

procedure Plant_createAspects1(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
  aspect := GsAspect.createWithInfo('kPlantAbsoluteTempForFrostKill_degC',
      'Absolute frost kill temperature',
      5022, 1, 1, false, 1, 
      1, 'params.absoluteTempForFrostKill_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 0.0, -30.0, 0.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantActualIncrease_tPha',
      'Actual increase in biomass today',
      5023, 1, 1, true, 4, 
      2, 'biomass.actualIncrease_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantAerationStressFactor_frn',
      'Aeration growth constraint today',
      5024, 1, 1, true, 4, 
      1, 'constraints.aerationStressFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantAge',
      'Plant age in days',
      5025, 2, 1, false, 2, 
      1, 'development.age', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantAluminumTolerance_pct',
      'Highest aluminum saturation plant can tolerate',
      5026, 1, 1, false, 1, 
      1, 'params.aluminumTolerance_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBaseTemp_degC',
      'Growth minimum temperature',
      5027, 1, 1, false, 1, 
      1, 'params.baseTemp_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 12.0, 0.0, 12.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassAdjustmentIfLAIDeclining',
      'Biomass reduction factor from declining LAI today',
      5028, 1, 1, true, 4, 
      1, 'constraints.biomassAdjustmentIfLAIDeclining', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassAdjustmentIfLAIDecliningFactor',
      'Adjustment to biomass-energy ratio if LAI declining',
      5029, 1, 1, false, 1, 
      1, 'params.biomassAdjustmentIfLAIDecliningFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassGrowthConstraint_frn',
      'Combined growth constraint today',
      5030, 1, 1, true, 4, 
      1, 'constraints.biomassGrowthConstraint_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassTempStressFactor_frn',
      'Temperature growth constraint today',
      5031, 1, 1, true, 4, 
      1, 'constraints.biomassTempStressFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassToEnergyRatio_kgPhaPMJ',
      'Photosynthate per unit of radiation',
      5032, 1, 1, false, 1, 
      1, 'params.biomassToEnergyRatio_kgPhaPMJ', false);
  aspect.addUnitsAndBounds(0, 17, 1, 1, 1, 10.0, 50.0, 10.0, 50.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassToEnergyRatioAtElevatedCO2_kgPhaPMJ',
      'Photosynthate per unit of radiation at elevated CO2 levels',
      5033, 1, 1, false, 1, 
      1, 'params.biomassToEnergyRatioAtElevatedCO2_kgPhaPMJ', false);
  aspect.addUnitsAndBounds(0, 17, 1, 1, 1, 10.0, 50.0, 10.0, 50.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassToEnergyRatioCO2Params',
      'S curve - effect of CO2 concentration on biomass-to-energy ratio / 100',
      5034, 1, 4, true, 1, 
      3, 'params.biomassToEnergyRatioCO2Params', false);
  aspect.addUnitsAndBounds(0, 17, 1, 1, 1, 330.0, 660.0, 300.0, 1000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantBiomassToEnergyRatioVPDParam',
      'Parameter relating biomass-energy ratio to VPD',
      5035, 1, 1, false, 1, 
      1, 'params.biomassToEnergyRatioVPDParam', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 999.0, 0.0, 999.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCanopyResistParam',
      'Canopy resistance for transpiration',
      5036, 1, 1, false, 1, 
      1, 'params.canopyResistParam', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCriticalAerationFactor_frn',
      'Critical aeration factor',
      5037, 1, 1, false, 1, 
      1, 'params.criticalAerationFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.75, 1.0, 0.75, 1.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumFloralInductionUnits',
      'Floral induction accumulated photothermal units',
      5038, 1, 1, false, 2, 
      1, 'development.cumFloralInductionUnits', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumFloralInitiationUnits',
      'Floral initiation accumulated thermal units',
      5039, 1, 1, false, 2, 
      1, 'development.cumFloralInitiationUnits', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumHeatUnits',
      'Cumulative heat units',
      5040, 1, 1, true, 2, 
      1, 'development.cumHeatUnits', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1000.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumPotPlantEvap_mm',
      'Cumulative potential transpiration',
      5041, 1, 1, true, 4, 
      1, 'water.cumPotPlantEvap_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumVernalizationUnits',
      'Vernalization accumulated thermal units',
      5042, 1, 1, false, 2, 
      1, 'development.cumVernalizationUnits', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantCumWaterUse_mm',
      'Cumulative water use',
      5043, 1, 1, true, 4, 
      1, 'water.cumWaterUse_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantDayPlanted',
      'Day planted, days from January 1',
      5044, 2, 1, true, 4, 
      1, 'development.dayPlanted', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantDaysGerminating',
      'Days seed has been germinating',
      5045, 2, 1, false, 4, 
      1, 'development.daysGerminating', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 10000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantDiameter_m',
      'Plant area covered',
      5046, 1, 1, true, 4, 
      1, 'biomass.diameter_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFloralInductionParams',
      'S Curve - effect of hours of darkness on fraction of floral induction day',
      5047, 1, 4, false, 1, 
      3, 'params.floralInductionParams', false);
  aspect.addUnitsAndBounds(0, 24, 1, 1, 1, 0.0, 24.0, 0.0, 24.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFlowersAndFruits_tPha',
      'Total fruit/flower biomass',
      5048, 1, 1, true, 2, 
      2, 'biomass.flowersAndFruits_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFractionOfGrowingSeasonWhenLeafDeclineStarts_frn',
      'Heat unit index when LAI decline starts',
      5049, 1, 1, false, 1, 
      1, 'params.fractionOfGrowingSeasonWhenLeafDeclineStarts_frn', true);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.4, 0.99, 0.4, 0.99, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFractionReproductiveAllocationAtMaturity_frn',
      'Reproductive fraction of total biomass at maturity, by weight',
      5050, 1, 1, false, 1, 
      1, 'params.fractionReproductiveAllocationAtMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFractionRootWtAtEmergence_frn',
      'Root fraction of total biomass at emergence, by weight',
      5051, 1, 1, false, 1, 
      1, 'params.fractionRootWtAtEmergence_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 0.99, 0.0, 10.99, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFractionRootWtAtMaturity_frn',
      'Root fraction of total biomass at maturity, by weight',
      5052, 1, 1, false, 1, 
      1, 'params.fractionRootWtAtMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 0.99, 0.0, 0.99, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFractionStorageOrganAllocationAtMaturity_frn',
      'Storage organ fraction of total biomass at maturity, by weight',
      5053, 1, 1, false, 1, 
      1, 'params.fractionStorageOrganAllocationAtMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantFrostReductionFactorParams',
      'S Curve - effect of air temperature (below freezing) on frost damage',
      5054, 1, 4, false, 1, 
      3, 'params.frostReductionFactorParams', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 0.0, -30.0, 0.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreAerationStress',
      'Ignore aeration stress (waterlogging)',
      5055, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreAerationStress]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreAluminumToxicity',
      'Ignore aluminum toxicity of soil',
      5056, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreAluminumToxicity]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreGerminationRequirements',
      'Ignore germination requirements',
      5057, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreGerminationRequirements]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreLeafSenescence',
      'Ignore leaf senescence',
      5058, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreLeafSenescence]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreLifeCycleLimits',
      'Ignore annual/biennial limits on life cycle',
      5059, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreLifeCycleLimits]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnorePhotoperiod',
      'Ignore photoperiod for flowering and fruiting',
      5060, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnorePhotoperiod]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsIgnoreReproductiveDecay',
      'Ignore fruit decay',
      5061, 8, 1, false, 1, 
      1, 'options[kPlantOptionsIgnoreReproductiveDecay]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalNitrogenUptake',
      'Act as if nitrogen uptake were optimal',
      5062, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalNitrogenUptake]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalPhosphorusUptake',
      'Act as if phosphorus uptake were optimal',
      5063, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalPhosphorusUptake]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalRadiation',
      'Use maximum possible radiation to calculate photosynthesis',
      5064, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalRadiation]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalSoilStrengthForRootGrowth',
      'Act as if soil strength were optimal for root growth',
      5065, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalSoilStrengthForRootGrowth]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalTemperature',
      'Act as if temperature were optimal',
      5066, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalTemperature]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantGrowthOptionsOptimalWaterUptake',
      'Act as if water uptake were optimal',
      5067, 8, 1, false, 1, 
      1, 'options[kPlantOptionsOptimalWaterUptake]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitFactorForLAIAndHeight',
      'Heat unit factor for LAI and height',
      5068, 1, 1, true, 4, 
      1, 'development.heatUnitFactorForLAIAndHeight', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitFactorParamsForLAI',
      'S Curve - effect of heat unit index on fraction of max leaf area index possible',
      5069, 1, 4, false, 1, 
      3, 'params.heatUnitFactorParamsForLAI', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitIndex',
      'Heat unit index',
      5070, 1, 1, true, 4, 
      1, 'development.heatUnitIndex', true);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 2.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitIndexAtEndOfVegetativePhase',
      'Heat unit index when vegetative phase ends',
      5071, 1, 1, false, 1, 
      1, 'params.heatUnitIndexAtEndOfVegetativePhase', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitIndexAtStartOfStorageOrganAllocation',
      'Heat unit index at start of storage organ allocation',
      5072, 1, 1, false, 4, 
      1, 'params.heatUnitIndexAtStartOfStorageOrganAllocation', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeatUnitIndexWhenReproductiveAllocationStarted',
      'Heat unit index when reproductive allocation started',
      5073, 1, 1, true, 4, 
      1, 'development.heatUnitIndexWhenReproductiveAllocationStarted', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHeight_m',
      'Plant height',
      5074, 1, 1, true, 2, 
      1, 'biomass.height_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantHoursAboveMinDayLengthWhenWinterGrowthCanOccur_hr',
      'Hours above minimum day length for year when winter growth can occur',
      5075, 1, 1, false, 1, 
      1, 'params.hoursAboveMinDayLengthWhenWinterGrowthCanOccur_hr', false);
  aspect.addUnitsAndBounds(0, 24, 1, 1, 1, 0.0, 24.0, 0.0, 24.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantIsDead',
      'Plant is dead',
      5076, 8, 1, false, 2, 
      1, 'development.isDead', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantIsDormant',
      'Plant is in dormancy',
      5077, 8, 1, false, 2, 
      1, 'development.isDormant', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantIsLegume',
      'Plant is a legume',
      5078, 8, 1, false, 4, 
      1, 'params.isLegume', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantIsSupported',
      'Plant is supported',
      5079, 8, 1, false, 2, 
      1, 'development.isSupported', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantIsTree',
      'Plant is a tree',
      5080, 8, 1, false, 4, 
      1, 'params.isTree', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLeafAreaIndex',
      'Leaf area index (LAI) today',
      5081, 1, 1, true, 4, 
      1, 'development.leafAreaIndex', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 5.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLeafAreaIndexAtStartOfDecline',
      'Leaf area index at start of LAI decline',
      5082, 1, 1, true, 4, 
      1, 'development.leafAreaIndexAtStartOfDecline', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLeafAreaIndexDeclineRateFactor',
      'Rate of LAI decline',
      5083, 1, 1, false, 1, 
      1, 'params.leafAreaIndexDeclineRateFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLeafLossIndex_frn',
      'Leaf loss index for leaves removed',
      5084, 1, 1, true, 2, 
      1, 'constraints.leafLossIndex_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLeafResistIfVPDBelowThreshold_mPsec',
      'Leaf stomatal conductance maximum',
      5085, 1, 1, false, 1, 
      1, 'params.leafResistIfVPDBelowThreshold_mPsec', false);
  aspect.addUnitsAndBounds(0, 13, 1, 1, 3, 0.0, 5.0, 0.0, 5.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLifeCycleType',
      'Life cycle type',
      5086, 11, 1, false, 1, 
      1, 'params.lifeCycleType', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantLifeHistoryStage',
      'Plant life history stage',
      5087, 11, 1, false, 4, 
      1, 'development.lifeHistoryStage', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaturityDaysBeforeFirstFallFrost_days',
      'Maturity date as days before first fall frost (can be negative)',
      5088, 2, 1, false, 1, 
      1, 'params.maturityDaysBeforeFirstFallFrost_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxAnnualNFert_kgPha',
      'Maximum annual N fertilizer allowed for plant',
      5089, 1, 1, false, 1, 
      2, 'params.maxAnnualNFert_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 10000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 10000.0, 0.0, 10000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxDiameterSupported_m',
      'Diameter maximum when supported',
      5090, 1, 1, false, 1, 
      1, 'params.maxDiameterSupported_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxDiameterUnsupported_m',
      'Diameter maximum when unsupported',
      5091, 1, 1, false, 1, 
      1, 'params.maxDiameterUnsupported_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxHeightSupported_m',
      'Height maximum when supported',
      5092, 1, 1, false, 1, 
      1, 'params.maxHeightSupported_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.1, 3.0, 0.1, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxHeightUnsupported_m',
      'Height maximum when unsupported',
      5093, 1, 1, false, 1, 
      1, 'params.maxHeightUnsupported_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.1, 3.0, 0.1, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxLeafAreaIndex',
      'Leaf area index (LAI) maximum',
      5094, 1, 1, false, 1, 
      1, 'params.maxLeafAreaIndex', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.5, 10.0, 0.5, 10.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxPossibleHeatUnitsBeforeGerminationInAnyClimate_degC',
      'Maximum heat units required for germination if climate is hot',
      5095, 1, 1, false, 1, 
      1, 'params.MaxPossibleHeatUnitsBeforeGerminationInAnyClimate_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 100.0, 0.0, 3000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxPossibleHeatUnitsBeforeMaturityInAnyClimate_degC',
      'Maximum heat units at maturity if climate is hot',
      5096, 1, 1, false, 1, 
      1, 'params.MaxPossibleHeatUnitsBeforeMaturityInAnyClimate_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 3000.0, 0.0, 3000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxRootDepth_m',
      'Root depth maximum',
      5097, 1, 1, false, 1, 
      1, 'params.maxRootDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.5, 3.0, 0.5, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxRootSystemDiameter_m',
      'Root system diameter maximum',
      5098, 1, 1, false, 1, 
      1, 'params.maxRootSystemDiameter_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxTempForFloralInduction_degC',
      'Floral induction maximum temperature',
      5099, 1, 1, false, 1, 
      1, 'params.maxTempForFloralInduction_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 30.0, 0.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMaxTempForVernalization_degC',
      'Vernalization maximum temperature',
      5100, 1, 1, false, 1, 
      1, 'params.maxTempForVernalization_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -10.0, 30.0, -10.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinCropManagementFactor',
      'Crop management factor for water erosion',
      5101, 1, 1, false, 1, 
      1, 'params.minCropManagementFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.001, 0.5, 0.001, 0.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinHeatUnitsBeforeGermination_degC',
      'Heat units required for germination',
      5102, 1, 1, true, 1, 
      1, 'params.minHeatUnitsBeforeGermination_degC', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 300.0, 0.0, 3000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinPossibleHeatUnitsBeforeGerminationInAnyClimate_degC',
      'Minimum heat units required for germination if climate is cold',
      5103, 1, 1, false, 1, 
      1, 'params.MinPossibleHeatUnitsBeforeGerminationInAnyClimate_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 100.0, 0.0, 3000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinPossibleHeatUnitsBeforeMaturityInAnyClimate_degC',
      'Minimum heat units at maturity if climate is cold',
      5104, 1, 1, false, 1, 
      1, 'params.MinPossibleHeatUnitsBeforeMaturityInAnyClimate_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 3000.0, 0.0, 3000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinSoilWaterInPlowDepthForGermination_mm',
      'Minimum soil water in plow depth (0.2 m) for germination',
      5105, 1, 1, false, 1, 
      1, 'params.minSoilWaterInPlowDepthForGermination_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 100000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinTempForFloralInduction_degC',
      'Floral induction minimum temperature',
      5106, 1, 1, false, 1, 
      1, 'params.minTempForFloralInduction_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 30.0, 0.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMinTempForVernalization_degC',
      'Vernalization minimum temperature',
      5107, 1, 1, false, 1, 
      1, 'params.minTempForVernalization_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -10.0, 30.0, -10.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMobilizationOutOfRoots_tPha',
      'Root biomass remobilized to other plant parts today',
      5108, 1, 1, true, 4, 
      2, 'biomass.mobilizationOutOfRoots_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMobilizationOutOfShoots_tPha',
      'Shoot biomass remobilized to other plant parts today',
      5109, 1, 1, true, 4, 
      2, 'biomass.mobilizationOutOfShoots_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantMobilizationOutOfStorage_tPha',
      'Storage organ biomass remobilized to other plant parts today',
      5110, 1, 1, true, 4, 
      2, 'biomass.mobilizationOutOfStorage_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNDemandByLayer_kgPha',
      'N demand today',
      5111, 1, 2, true, 4, 
      2, 'nutrients.nDemandByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNDemandForOptimalGrowth_kgPha',
      'N demand for optimal growth today',
      5112, 1, 1, true, 4, 
      2, 'nutrients.nDemandForOptimalGrowth_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNFixation_kgPha',
      'N fixation today',
      5113, 1, 1, true, 4, 
      2, 'nutrients.nFixation_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNFixationParam_frn',
      'N fixation parameter',
      5114, 1, 1, false, 1, 
      1, 'params.nFixationParam_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNFractionAtEmergence_frn',
      'N optimal fraction in plant at emergence, by weight',
      5115, 1, 1, false, 1, 
      1, 'params.nFractionAtEmergence_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.04, 0.06, 0.04, 0.06, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNFractionAtHalfMaturity_frn',
      'N optimal fraction in plant at half-maturity, by weight',
      5116, 1, 1, false, 1, 
      1, 'params.nFractionAtHalfMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.015, 0.03, 0.015, 0.03, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNFractionAtMaturity_frn',
      'N optimal fraction in plant at maturity, by weight',
      5117, 1, 1, false, 1, 
      1, 'params.nFractionAtMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.01, 0.27, 0.01, 0.27, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNInLiveBiomass_kgPha',
      'N in live plant biomass',
      5118, 1, 1, false, 2, 
      2, 'nutrients.nInLiveBiomass_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNInStandingDead_kgPha',
      'N in standing dead biomass',
      5119, 1, 1, false, 2, 
      2, 'nutrients.nInStandingDead_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNonFixationNUptakeOverDemand_frn',
      'Ratio of N uptake over demand today',
      5120, 1, 1, true, 4, 
      1, 'nutrients.nonFixationNUptakeOverDemand_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNStressFactor_frn',
      'N growth constraint today',
      5121, 1, 1, true, 4, 
      1, 'constraints.nStressFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNSupplyByLayer_kgPha',
      'N supply today',
      5122, 1, 2, true, 4, 
      2, 'nutrients.nSupplyByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNumLayersWithRootsInThem',
      'Number of soil layers roots enter',
      5123, 2, 1, true, 4, 
      1, 'biomass.numLayersWithRootsInThem', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantNUptakeByLayer_kgPha',
      'N uptake today',
      5124, 1, 2, true, 4, 
      2, 'nutrients.nUptakeByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantOptimalNConc_kgPkg',
      'N optimal concentration today',
      5125, 1, 1, true, 4, 
      1, 'nutrients.optimalNConc_kgPkg', false);
  aspect.addUnitsAndBounds(0, 20, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantOptimalPConc_kgPkg',
      'P optimal concentration today',
      5126, 1, 1, true, 4, 
      1, 'nutrients.optimalPConc_kgPkg', false);
  aspect.addUnitsAndBounds(0, 20, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantOptimalTemp_degC',
      'Growth optimal temperature',
      5127, 1, 1, false, 1, 
      1, 'params.optimalTemp_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 10.0, 30.0, 10.0, 30.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantOptTempForFloralInduction_degC',
      'Floral induction optimal temperature',
      5128, 1, 1, false, 1, 
      1, 'params.optTempForFloralInduction_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, 0.0, 30.0, 0.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantOptTempForVernalization_degC',
      'Vernalization optimal temperature',
      5129, 1, 1, false, 1, 
      1, 'params.optTempForVernalization_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -10.0, 30.0, -10.0, 30.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPDemandByLayer_kgPha',
      'P demand today',
      5130, 1, 2, true, 4, 
      2, 'nutrients.pDemandByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPDemandForOptimalGrowth_kgPha',
      'P demand for optimal growth today',
      5131, 1, 1, true, 4, 
      2, 'nutrients.pDemandForOptimalGrowth_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPFractionAtEmergence_frn',
      'P optimal fraction in plant at emergence, by weight',
      5132, 1, 1, false, 1, 
      1, 'params.pFractionAtEmergence_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.006, 0.009, 0.006, 0.009, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPFractionAtHalfMaturity_frn',
      'P optimal fraction in plant at half-maturity, by weight',
      5133, 1, 1, false, 1, 
      1, 'params.pFractionAtHalfMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.002, 0.005, 0.002, 0.005, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPFractionAtMaturity_frn',
      'P optimal fraction in plant at maturity, by weight',
      5134, 1, 1, false, 1, 
      1, 'params.pFractionAtMaturity_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0015, 0.0035, 0.0015, 0.0035, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPhotoActiveRadiation_MJPm2',
      'Photosynthetically active radiation intercepted today',
      5135, 1, 1, true, 4, 
      1, 'biomass.photoActiveRadiation_MJPm2', false);
  aspect.addUnitsAndBounds(0, 10, 1, 1, 7, 0.0, 50.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPhotothermalUnitsRequiredForFloralInduction',
      'Floral induction photothermal units required',
      5136, 1, 1, false, 1, 
      1, 'params.photothermalUnitsRequiredForFloralInduction', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPInLiveBiomass_kgPha',
      'P in live plant biomass',
      5137, 1, 1, false, 2, 
      2, 'nutrients.pInLiveBiomass_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPInStandingDead_kgPha',
      'P in standing dead biomass',
      5138, 1, 1, false, 2, 
      2, 'nutrients.pInStandingDead_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantDaysToGrowOptimallyAfterPlanting_days',
      'Days from planting date to grow plant optimally (as if in a greenhouse)',
      5139, 2, 1, false, 1, 
      1, 'params.daysToGrowOptimallyAfterPlanting_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantingDaysAfterLastSpringFrost_days',
      'Planting date as days after first spring frost (can be negative)',
      5140, 2, 1, false, 1, 
      1, 'params.plantingDaysAfterLastSpringFrost_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantingDaysFromGerminatedSeedToSeasonMaturity_days',
      'Days from emergence to season maturity',
      5141, 2, 1, false, 1, 
      1, 'params.plantingDaysFromGerminatedSeedToSeasonMaturity_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantingDaysFromSeedToGerminatedSeed_days',
      'Days from planting to germination',
      5142, 2, 1, false, 1, 
      1, 'params.plantingDaysFromSeedToGerminatedSeed_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantingDepth_mm',
      'Planting depth',
      5143, 1, 1, false, 1, 
      1, 'params.plantingDepth_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantingSpringFallOrBoth',
      'Calculate growing season from spring planting, fall harvest or either',
      5144, 11, 1, false, 1, 
      1, 'params.plantingSpringFallOrBoth', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPlantNAndPStressCoeffs',
      'S Curve - effect of actual/potential N or P ratio on N or P stress ',
      5145, 1, 4, false, 1, 
      3, 'params.plantNAndPStressCoeffs', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPotentialIncrease_tPha',
      'Potential increase in biomass today',
      5146, 1, 1, true, 4, 
      2, 'biomass.potentialIncrease_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPotHeatUnitsReqForMaturation',
      'Potential heat units at maturity',
      5147, 1, 1, true, 1, 
      1, 'params.potHeatUnitsReqForMaturation', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 3000.0, 0.0, 3000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPotPlantEvap_mm',
      'Potential transpiration today',
      5148, 1, 1, true, 4, 
      1, 'water.potPlantEvap_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantProbOfGerminationAfterFirstYear_frn',
      'Probability of seed survival after first winter',
      5149, 1, 1, false, 1, 
      1, 'params.probOfGerminationAfterFirstYear_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPStressFactor_frn',
      'P growth constraint today',
      5150, 1, 1, true, 4, 
      1, 'constraints.pStressFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPSupplyByLayer_kgPha',
      'P supply today',
      5151, 1, 2, true, 4, 
      2, 'nutrients.pSupplyByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPUptakeByLayer_kgPha',
      'P uptake today',
      5152, 1, 2, true, 4, 
      2, 'nutrients.pUptakeByLayer_kgPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPUptakeCoeffs',
      'S Curve - effect of labile P concentration on phosphorus uptake',
      5153, 1, 4, false, 1, 
      3, 'params.pUptakeCoeffs', false);
  aspect.addUnitsAndBounds(0, 25, 1, 1, 1, 0.0, 40.0, 0.0, 40.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantPUptakeOverDemand',
      'Ratio of P uptake over demand today',
      5154, 1, 1, true, 4, 
      1, 'nutrients.pUptakeOverDemand', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 3.0, -1000000.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReductionFromDryness_tPha',
      'Biomass lost from water stress today',
      5155, 1, 1, true, 4, 
      2, 'biomass.reductionFromDryness_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReductionFromFallingLeaves_tPha',
      'Biomass lost from falling leaves (if tree) today',
      5156, 1, 1, true, 4, 
      2, 'biomass.reductionFromFallingLeaves_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReductionFromFrostAndDaylength_tPha',
      'Biomass lost from frost and day length today',
      5157, 1, 1, true, 4, 
      2, 'biomass.reductionFromFrostAndDaylength_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReductionFromReproductiveDecay_tPha',
      'Biomass lost from fruit decay today',
      5158, 1, 1, true, 4, 
      2, 'biomass.reductionFromReproductiveDecay_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReductionInStandingDeadFromTransferToResidue_tPha',
      'Standing dead biomass transferred to mulch residue today',
      5159, 1, 1, true, 4, 
      2, 'biomass.reductionInStandingDeadFromTransferToResidue_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReproductiveAllocation_tPha',
      'Allocation to flowers and fruits today',
      5160, 1, 1, true, 4, 
      2, 'biomass.reproductiveAllocation_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantReproductiveBiomassDecayAtPlantMaturity',
      'Fruit biomass daily decay fraction at plant maturity, by weight',
      5161, 1, 1, false, 1, 
      1, 'params.reproductiveBiomassDecayAtPlantMaturity', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootAllocationByLayer_tPha',
      'Allocation to roots today',
      5162, 1, 2, true, 4, 
      2, 'biomass.rootAllocationByLayer_tPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootAlStressFactorByLayer_frn',
      'Aluminum toxicity constraint on root growth today',
      5163, 1, 2, true, 4, 
      1, 'constraints.rootAlStressFactorByLayer_frn[index]', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootDepth_m',
      'Root depth',
      5164, 1, 1, true, 2, 
      1, 'biomass.rootDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootGrowthConstraintByLayer_frn',
      'Combined constraint on root growth today',
      5165, 1, 2, true, 4, 
      1, 'constraints.rootGrowthConstraintByLayer_frn[index]', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootGrowthRestrictionByAerationStress',
      'S Curve - effect of aeration stress on root growth restriction',
      5166, 1, 4, false, 1, 
      3, 'params.rootGrowthRestrictionByAerationStress', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootGrowthRestrictionByRockCoeffs',
      'S Curve - effect of rock content on root growth restriction',
      5167, 1, 4, false, 1, 
      3, 'params.rootGrowthRestrictionByRockCoeffs', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootSoilStrengthFactorByLayer_frn',
      'Soil strength constraint on root growth today',
      5168, 1, 2, true, 4, 
      1, 'constraints.rootSoilStrengthFactorByLayer_frn[index]', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootSystemDiameter_m',
      'Root system diameter',
      5169, 1, 1, true, 4, 
      1, 'biomass.rootSystemDiameter_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootTempStressFactorByLayer_frn',
      'Temperature constraint on root growth today',
      5170, 1, 2, true, 4, 
      1, 'constraints.rootTempStressFactorByLayer_frn[index]', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantRootWeightByLayer_tPha',
      'Root biomass ',
      5171, 1, 2, true, 2, 
      2, 'biomass.rootWeightByLayer_tPha[index]', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantSeedWeight_g',
      'Weight of one seed',
      5172, 1, 1, false, 1, 
      1, 'params.seedWeight_g', false);
  aspect.addUnitsAndBounds(0, 6, 2, 2, 5, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
    end;

procedure Plant_createAspects2(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
  aspect := GsAspect.createWithInfo('kPlantShootAllocation_tPha',
      'Allocation to all shoots today',
      5173, 1, 1, true, 4, 
      2, 'biomass.shootAllocation_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantSnowCoverFactorForFrostKill',
      'Snow cover factor for frost kill today',
      5174, 1, 1, true, 4, 
      1, 'constraints.snowCoverFactorForFrostKill', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantStandingDead_tPha',
      'Standing dead plant residue (above-ground)',
      5175, 1, 1, true, 2, 
      2, 'biomass.standingDead_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantStandingLive_tPha',
      'Above-ground live biomass',
      5176, 1, 1, true, 3, 
      2, 'biomass.standingLive_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantStorageOrgan_tPha',
      'Biomass of all storage organs',
      5177, 1, 1, true, 2, 
      2, 'biomass.storageOrgan_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantStorageOrganAllocation_tPha',
      'Allocation to all storage organs today',
      5178, 1, 1, true, 4, 
      2, 'biomass.storageOrganAllocation_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantThermalUnitsRequiredForFloralInitiation',
      'Floral initiation thermal units required',
      5179, 1, 1, false, 1, 
      1, 'params.thermalUnitsRequiredForFloralInitiation', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantThermalUnitsRequiredForVernalization',
      'Vernalization thermal units required',
      5180, 1, 1, false, 1, 
      1, 'params.thermalUnitsRequiredForVernalization', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 50.0, 0.0, 50.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantThresholdVaporPressureDeficit_kPa',
      'Vapor pressure deficit (VPD) threshold',
      5181, 1, 1, false, 1, 
      1, 'params.thresholdVaporPressureDeficit_kPa', false);
  aspect.addUnitsAndBounds(0, 14, 2, 2, 7, 0.0, 500.0, 0.0, 999.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantTotalInclRoot_tPha',
      'Total live biomass including root',
      5182, 1, 1, true, 3, 
      2, 'biomass.totalLive_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantTotalShootWeight_tPha',
      'Biomass of all leaves and stems',
      5183, 1, 1, true, 2, 
      2, 'biomass.totalShootWeight_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantVernalizationRequirement',
      'Vernalization requirement',
      5184, 11, 1, false, 1, 
      1, 'params.vernalizationRequirement', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantVPDAboveThresholdAtThreeQuartersMaxLeafConductance_kPa',
      'VPD at which leaf conductance is 75% of maximum',
      5185, 1, 1, false, 1, 
      1, 'params.fractionOfMaxLeafConductForHighVPD.x', false);
  aspect.addUnitsAndBounds(0, 14, 2, 2, 7, 0.0, 500.0, 0.0, 999.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWaterDemandByLayer_mm',
      'Water demand today',
      5186, 1, 2, true, 4, 
      1, 'water.waterDemandByLayer_mm[index]', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWaterStressFactor_frn',
      'Water stress growth constraint today',
      5187, 1, 1, true, 4, 
      1, 'constraints.waterStressFactor_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWaterUseByLayer_mm',
      'Water use today',
      5188, 1, 2, true, 4, 
      1, 'water.waterUseByLayer_mm[index]', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWindErosionFactorFlatResidue',
      'Wind erosion factor for flat residue',
      5189, 1, 1, false, 1, 
      1, 'params.windErosionFactorFlatResidue', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.2, 3.5, 0.2, 3.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWindErosionFactorStandingDead',
      'Wind erosion factor for standing dead residue',
      5190, 1, 1, false, 1, 
      1, 'params.windErosionFactorStandingDead', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.4, 3.5, 0.4, 3.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWindErosionFactorStandingLive',
      'Wind erosion factor for standing live biomass',
      5191, 1, 1, false, 1, 
      1, 'params.windErosionFactorStandingLive', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.4, 3.5, 0.4, 3.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWinterBiomassDayLengthReductionFactor',
      'Biomass reduction factor from day length today',
      5192, 1, 1, true, 4, 
      1, 'constraints.winterBiomassDayLengthReductionFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWinterBiomassFrostReductionFactor',
      'Biomass reduction factor from frost today',
      5193, 1, 1, true, 4, 
      1, 'constraints.winterBiomassFrostReductionFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantWinterBiomassReductionFactor',
      'Biomass reduction factor from frost and day length combined today',
      5194, 1, 1, true, 4, 
      1, 'constraints.winterBiomassReductionFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, 0.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantYearsOld',
      'Plant age in years',
      5195, 2, 1, true, 4, 
      1, 'development.yearsOld', false);
  aspect.addUnitsAndBounds(0, 22, 1, 1, 1, 0.0, 10.0, 0.0, 1000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantYearsToMaturityIfTree',
      'If tree, years to maturity',
      5196, 1, 1, false, 1, 
      1, 'params.yearsToMaturityIfTree', false);
  aspect.addUnitsAndBounds(0, 22, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kPlantYesterdaysHeatUnitFactorForLAIAndHeight',
      'Yesterday''s heat unit factor for LAI and height',
      5197, 1, 1, true, 4, 
      1, 'development.yesterdaysHeatUnitFactorForLAIAndHeight', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
    end;

end.
