unit uasp_s1;
{Copyright (c) 1997 Paul D. Fernhout and Cynthia F. Kurtz All rights reserved
http://www.gardenwithinsight.com. See the license file for details on redistribution.
=====================================================================================
DO NOT EDIT THIS FILE. It was generated by the tab2asp program from aspects.tab.
uasp_s1: Aspect creation for soil patch (part 1).}

interface

uses uaspects;

procedure SoilPatch_createAspects1(aspectManager: GsAspectManager);

implementation

procedure SoilPatch_createAspects1(aspectManager: GsAspectManager);
  var aspect: GsAspect;
  begin
  aspect := GsAspect.createWithInfo('kSoilPatchAlbedo_frn',
      'Albedo at soil surface today',
      5380, 1, 1, true, 4, 
      1, 'surface.albedo_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAmmoniaAdsorbedToSediment_kgPha',
      'Ammonia lost in eroded soil today',
      5381, 1, 1, true, 4, 
      2, 'movement.ammoniaAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchArea_ha',
      'Soil patch area',
      5382, 1, 1, true, 1, 
      1, 'params.area_ha', false);
  aspect.addUnitsAndBounds(0, 8, 1, 2, 4, 0.00001, 1.0, 0.00001, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAutoIrrigationForDay_mm',
      'Auto irrigation today',
      5383, 1, 1, true, 4, 
      1, 'water.autoIrrigationForDay_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAutoIrrigationIsByFurrow',
      'Auto irrigation is by furrow (not sprinkler)',
      5384, 8, 1, false, 1, 
      1, 'params.autoIrrigationIsByFurrow', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAvgCurveNumber',
      'Average curve number for runoff today',
      5385, 1, 1, true, 4, 
      1, 'water.avgCurveNumber', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 30.0, 95.0, 30.0, 95.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAvgCurveNumberUnadjustedForSlope',
      'Average SCS II curve number for runoff (not adjusted for slope)',
      5386, 1, 1, false, 1, 
      1, 'params.avgCurveNumberUnadjustedForSlope', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 30.0, 95.0, 30.0, 95.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchAvgNConcInRainfall_gPm3',
      'Average nitrogen concentration in rainfall',
      5387, 1, 1, false, 1, 
      1, 'params.avgNConcInRainfall_gPm3', true);
  aspect.addUnitsAndBounds(0, 25, 1, 1, 1, 0.5, 1.5, 0.5, 1.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchBaseDrawingColor',
      'Base color for dry soil with low organic matter',
      5388, 7, 1, false, 1, 
      1, 'params.baseDrawingColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCarbonDioxideInAtmosphere_ppm',
      'CO2 concentration in atmosphere',
      5389, 1, 1, false, 1, 
      1, 'params.carbonDioxideInAtmosphere_ppm', false);
  aspect.addUnitsAndBounds(0, 25, 1, 1, 1, 50.0, 2000.0, 50.0, 2000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchChangeInPatchTotalNitrate_kgPha',
      'Change in total nitrate today',
      5390, 1, 1, true, 4, 
      2, 'movement.changeInPatchTotalNitrate_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCumIrrigationApplied_mm',
      'Cumulative irrigation applied for year',
      5391, 1, 1, true, 4, 
      1, 'yearTotals.cumIrrigationApplied_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCumNAddedInIrrigationWater_kgPha',
      'N as nitrate added in irrigation water this year',
      5392, 1, 1, true, 4, 
      2, 'yearTotals.cumNAddedInIrrigationWater_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCumNFertAutoApplied_kgPha',
      'N fertilizer applied this year',
      5393, 1, 1, true, 4, 
      2, 'yearTotals.cumNFertAutoApplied_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCumNFixation_kgPha',
      'N fixed this year',
      5394, 1, 1, true, 4, 
      2, 'yearTotals.cumNFixation_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCumPFertAutoApplied_kgPha',
      'P fertilizer added this year',
      5395, 1, 1, true, 4, 
      2, 'yearTotals.cumPFertAutoApplied_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchCurveNumber',
      'Curve number for runoff today',
      5396, 1, 1, true, 4, 
      1, 'water.curveNumber', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDaysSinceAutoFertApplied',
      'Days since auto fertilization was applied',
      5397, 2, 1, true, 2, 
      1, 'state.daysSinceAutoFertApplied', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDaysSinceAutoIrrApplied',
      'Days since auto irrigation was applied',
      5398, 2, 1, true, 2, 
      1, 'state.daysSinceAutoIrrApplied', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDikeHeight_mm',
      'Furrow dike height today',
      5399, 1, 1, false, 2, 
      1, 'surface.dikeHeight_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDikeHeightAtCreation_mm',
      'Furrow dike height when created',
      5400, 1, 1, false, 2, 
      1, 'surface.dikeHeightAtCreation_mm', false);
  aspect.addUnitsAndBounds(0, 2, 2, 3, 6, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDikeInterval_m',
      'Furrow dike interval',
      5401, 1, 1, false, 2, 
      1, 'surface.dikeInterval_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDikesNeedRebuilt',
      'Furrow dikes need to be rebuilt',
      5402, 8, 1, false, 4, 
      1, 'surface.dikesNeedRebuilt', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchDikeVolume_mm',
      'Furrow dike volume',
      5403, 1, 1, true, 4, 
      1, 'surface.dikeVolume_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchEnrichmentRatioForNPPest',
      'Enrichment ratio for N and P today',
      5404, 1, 1, true, 4, 
      1, 'erosion.enrichmentRatioForNPPest', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchErosionControlPracticeFactor',
      'Erosion control practice factor for water erosion',
      5405, 1, 1, false, 1, 
      1, 'params.erosionControlPracticeFactor', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFlatCropResidueAddedFromDeadPlant_tPha',
      'Flat residue newly decayed from organic matter blobs today',
      5406, 1, 1, true, 4, 
      2, 'movement.flatCropResidueAddedFromDeadPlant_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFlatCropResidueAdsorbedToSediment_kgPha',
      'Flat residue lost in eroded soil today',
      5407, 1, 1, true, 4, 
      2, 'movement.flatCropResidueAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFlatCropResidueDecomposedToAtmosphere_tPha',
      'Flat residue decomposed to atmosphere today',
      5408, 1, 1, true, 4, 
      2, 'movement.flatCropResidueDecomposedToAtmosphere_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFlatCropResidueDecomposedToOrganicMatter_tPha',
      'Flat residue decomposed to organic matter today',
      5409, 1, 1, true, 4, 
      2, 'movement.flatCropResidueDecomposedToOM_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFlatCropResidueFromOM_tPha',
      'Undecayed dead plant matter (in organic matter blobs) on this soil patch',
      5410, 1, 1, true, 4, 
      2, 'movement.flatCropResidueFromOM_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFractDikeVolAvailForWaterStorage_frn',
      'Furrow dike fraction of volume available for water storage',
      5411, 1, 1, false, 1, 
      1, 'params.fractDikeVolAvailForWaterStorage_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchFractionIrrigLostToRunoff',
      'Fraction of irrigation water lost to runoff',
      5412, 1, 1, false, 1, 
      1, 'params.fractionOfIrrigationWaterLostToRunoff', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 0.6, 0.0, 0.6, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchIgnoreNContentWhenAutoFertilizing',
      'Ignore N content when auto fertilizing',
      5413, 8, 1, false, 1, 
      1, 'params.ignoreNContentWhenAutoFertilizing', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchIgnoreSoilWaterContentWhenIrrigating',
      'Ignore soil water content when irrigating',
      5414, 8, 1, false, 1, 
      1, 'params.ignoreSoilWaterContentWhenAutoIrrigating', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchInflowFromWaterTable_mm',
      'Water table inflow to patch today',
      5415, 1, 1, true, 4, 
      1, 'water.inflowFromWaterTable_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchIrrigationPeakRunoffRate_m3Psec',
      'Peak runoff rate from irrigation today',
      5416, 1, 1, true, 4, 
      1, 'water.irrigationPeakRunoffRate_m3Psec', false);
  aspect.addUnitsAndBounds(0, 29, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchIrrigationRunoffVolume_mm',
      'Runoff volume from irrigation today',
      5417, 1, 1, true, 4, 
      1, 'water.irrigationRunoffVolume_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchIrrigationWaterErosion_tPha',
      'Water erosion from irrigation today',
      5418, 1, 1, true, 4, 
      2, 'erosion.irrigationWaterErosion_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLabilePAdsorbedToSediment_kgPha',
      'P as labile lost in eroded soil today',
      5419, 1, 1, true, 4, 
      2, 'movement.labilePAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLabilePLostInRunoff_kgPha',
      'P as labile lost in runoff today',
      5420, 1, 1, true, 4, 
      2, 'movement.labilePLostInRunoff_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerActiveHumusNMineralization_kgPha',
      'N as active organic in humus mineralized today by layer',
      5421, 1, 2, true, 4, 
      2, 'layers[index].activeHumusNMineralization_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerActiveHumusPMineralization_kgPha',
      'P as organic in humus mineralized today by layer',
      5422, 1, 2, true, 4, 
      2, 'layers[index].activeHumusPMineralization_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerAluminumSaturation_pct',
      'Aluminum saturation by layer',
      5423, 1, 2, true, 2, 
      1, 'layers[index].aluminumSaturation_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerAmmonia_kgPha',
      'N as ammonia by layer',
      5424, 1, 2, false, 2, 
      2, 'layers[index].ammonia_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerBaseFormingCations_cmolPkg',
      'Base-forming cations by layer',
      5425, 1, 2, false, 2, 
      1, 'layers[index].baseFormingCations_cmolPkg', false);
  aspect.addUnitsAndBounds(0, 16, 1, 1, 1, 0.0, 150.0, 0.0, 150.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerBulkDensity_tPm3',
      'Bulk density by layer',
      5426, 1, 2, false, 2, 
      1, 'layers[index].bulkDensity_tPm3', true);
  aspect.addUnitsAndBounds(0, 15, 3, 1, 4, 0.0, 5.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerBulkDensityOvenDry_tPm3',
      'Bulk density oven-dry by layer',
      5427, 1, 2, false, 2, 
      1, 'layers[index].bulkDensityOvenDry_tPm3', false);
  aspect.addUnitsAndBounds(0, 15, 3, 1, 4, 0.0, 2.5, 0.0, 2.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerCalciumCarbonate_pct',
      'Free calcium carbonate by layer',
      5428, 1, 2, false, 2, 
      1, 'layers[index].calciumCarbonate_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerCationExchangeCapacity_cmolPkg',
      'Cation exchange capacity by layer',
      5429, 1, 2, false, 2, 
      1, 'layers[index].cationExchangeCapacity_cmolPkg', false);
  aspect.addUnitsAndBounds(0, 16, 1, 1, 1, 0.0, 150.0, 0.0, 150.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerClayContent_pct',
      'Clay content by layer',
      5430, 1, 2, false, 2, 
      1, 'layers[index].clayContent_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerDecayRateConst',
      'Residue decay rate today by layer',
      5431, 1, 2, true, 4, 
      1, 'layers[index].decayRateConst', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerDenitrification_kgPha',
      'Denitrification today by layer',
      5432, 1, 2, true, 4, 
      2, 'layers[index].denitrification_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerDepth_m',
      'Depth by layer',
      5433, 1, 2, false, 2, 
      1, 'layers[index].depth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerEvaporation_mm',
      'Evaporation from layer today',
      5434, 1, 2, true, 4, 
      2, 'layers[index].evaporation_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerFieldCapacity_mm',
      'Field capacity by layer',
      5435, 1, 2, false, 2, 
      2, 'layers[index].fieldCapacity_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerFlatCropResidue_tPha',
      'Flat residue by layer',
      5436, 1, 2, false, 2, 
      2, 'layers[index].flatCropResidue_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerFreshNMineralization_kgPha',
      'N as fresh organic in flat residue mineralized today by layer',
      5437, 1, 2, true, 4, 
      2, 'layers[index].freshNMineralization_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerFreshPMineralization_kgPha',
      'P as fresh organic in flat residue mineralized today by layer',
      5438, 1, 2, true, 4, 
      2, 'layers[index].freshPMineralization_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerLabileP_kgPha',
      'P as labile by layer',
      5439, 1, 2, false, 2, 
      2, 'layers[index].labileP_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 50.0, 0.0, 50.0, 1);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerLabilePLeachedFromPercolation_kgPha',
      'P as labile leached from percolation today by layer',
      5440, 1, 2, true, 4, 
      2, 'layers[index].labilePLeachedFromPercolation_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerLateralFlow_mm',
      'Sub-surface flow out of layer today',
      5441, 1, 2, true, 4, 
      2, 'layers[index].lateralFlow_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerMineralPActive_kgPha',
      'P as active mineral by layer',
      5442, 1, 2, false, 2, 
      2, 'layers[index].mineralPActive_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerMineralPFlowCoeff_Pday',
      'P mineral flow coefficient today by layer',
      5443, 1, 2, true, 4, 
      1, 'layers[index].mineralPFlowCoeff_Pday', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerMineralPFlowFromActiveToStable_kgPha',
      'P flow from active to stable mineral today by layer',
      5444, 1, 2, true, 4, 
      2, 'layers[index].mineralPFlowFromActiveToStable_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerMineralPStable_kgPha',
      'P as stable mineral by layer',
      5445, 1, 2, false, 2, 
      2, 'layers[index].mineralPStable_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerNitrate_kgPha',
      'N as nitrate by layer',
      5446, 1, 2, false, 2, 
      2, 'layers[index].nitrate_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 30.0, 0.0, 30.0, 1);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerNitrateLeachedFromLateralFlow_kgPha',
      'N as nitrate leached from sub-surface flow today by layer',
      5447, 1, 2, true, 4, 
      2, 'layers[index].nitrateLeachedFromLateralFlow_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerNitrateLeachedFromPercolation_kgPha',
      'N as nitrate leached from percolation today by layer',
      5448, 1, 2, true, 4, 
      2, 'layers[index].nitrateLeachedFromPercolation_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerNitrification_kgPha',
      'N nitrification today by layer',
      5449, 1, 2, true, 4, 
      2, 'layers[index].nitrification_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerNutrientCyclingTempFactor',
      'Nutrient cycling temperature factor today by layer',
      5450, 1, 2, true, 4, 
      1, 'layers[index].nutrientCyclingTempFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 1.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicMatter_tPha',
      'Organic matter by layer',
      5451, 1, 2, false, 2, 
      2, 'layers[index].organicMatter_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicNActiveHumus_kgPha',
      'N as active organic in humus by layer',
      5452, 1, 2, false, 2, 
      2, 'layers[index].organicNActiveHumus_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicNFresh_kgPha',
      'N as fresh organic in flat residue by layer',
      5453, 1, 2, false, 2, 
      2, 'layers[index].organicNFresh_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicNFromActiveToStableInHumus_kgPha',
      'N flow from active to stable in humus today by layer',
      5454, 1, 2, true, 4, 
      2, 'layers[index].organicNFromActiveToStableInHumus_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicNStableHumus_kgPha',
      'N as stable organic in humus by layer',
      5455, 1, 2, false, 2, 
      2, 'layers[index].organicNStableHumus_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicPFresh_kgPha',
      'P as fresh organic in flat residue by layer',
      5456, 1, 2, false, 2, 
      2, 'layers[index].organicPFresh_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerOrganicPHumus_kgPha',
      'P as organic in humus by layer',
      5457, 1, 2, false, 2, 
      2, 'layers[index].organicPHumus_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerPercolation_mm',
      'Percolation through layer today',
      5458, 1, 2, true, 4, 
      2, 'layers[index].percolation_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerPFlowFromLabileToActiveMineral_kgPha',
      'P flow from labile to active mineral today by layer',
      5459, 1, 2, true, 4, 
      2, 'layers[index].pFlowFromLabileToActiveMineral_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerPorosity_mm',
      'Porosity by layer',
      5460, 1, 2, false, 2, 
      2, 'layers[index].porosity_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 100.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerPSorptionCoeff_frn',
      'P sorption coefficient today by layer',
      5461, 1, 2, true, 4, 
      1, 'layers[index].pSorptionCoeff_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerRockContent_pct',
      'Rock content by layer',
      5462, 1, 2, false, 2, 
      1, 'layers[index].rockContent_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 30.0, 0.0, 30.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerSandContent_pct',
      'Sand content by layer',
      5463, 1, 2, false, 2, 
      1, 'layers[index].sandContent_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerSaturatedConductivity_mmPhr',
      'Saturated conductivity by layer',
      5464, 1, 2, false, 2, 
      1, 'layers[index].saturatedConductivity_mmPhr', false);
  aspect.addUnitsAndBounds(0, 13, 2, 2, 5, 0.0, 50.0, 0.0, 50.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerSettledBulkDensity_tPm3',
      'Bulk density settled by layer',
      5465, 1, 2, false, 2, 
      1, 'layers[index].settledBulkDensity_tPm3', false);
  aspect.addUnitsAndBounds(0, 15, 3, 1, 4, 0.25, 2.3, 0.25, 2.3, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerSiltContent_pct',
      'Silt content by layer',
      5466, 1, 2, false, 2, 
      1, 'layers[index].siltContent_pct', false);
  aspect.addUnitsAndBounds(0, 27, 1, 1, 1, 0.0, 100.0, 0.0, 100.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerSoilpH',
      'pH by layer',
      5467, 1, 2, false, 2, 
      1, 'layers[index].soilpH', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 4.0, 9.0, 4.0, 9.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerTemperature_degC',
      'Temperature today by layer',
      5468, 1, 2, true, 4, 
      1, 'layers[index].temperature_degC', false);
  aspect.addUnitsAndBounds(0, 5, 1, 1, 2, -30.0, 40.0, -1000000.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerTravelTimeFactor',
      'Travel time factor for water flow today by layer',
      5469, 1, 2, true, 4, 
      1, 'layers[index].travelTimeFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 24.0, 0.0, 24.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerVolatilization_kgPha',
      'Volatilization today by layer',
      5470, 1, 2, true, 4, 
      2, 'layers[index].volatilization_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerWaterContent_mm',
      'Water content by layer',
      5471, 1, 2, false, 2, 
      2, 'layers[index].waterContent_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.0, 1.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerWeight_tPha',
      'Weight by layer',
      5472, 1, 2, false, 2, 
      2, 'layers[index].weight_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerWiltingPoint_mm',
      'Wilting point by layer',
      5473, 1, 2, false, 2, 
      2, 'layers[index].wiltingPoint_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(1, 21, 1, 1, 1, 0.01, 0.65, 0.01, 0.65, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLayerWithDrainageSystem',
      'Layer containing drainage system',
      5474, 2, 1, false, 2, 
      1, 'params.layerWithDrainageSystem', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLowerLimitWaterContentInTopP5MAsFractOfWP_frn',
      'Fraction of wilting point to which plants can pull water out of top 0.5m of soil',
      5475, 1, 1, false, 1, 
      1, 'params.lowerLimitWaterContentInTopP5MAsFractOfWP_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchLowestLayerInWhichSoilEvapOccured',
      'Lowest layer in which soil evaporation occurred today',
      5476, 2, 1, true, 4, 
      1, 'water.lowestLayerInWhichSoilEvapOccured', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 1.0, 10.0, 1.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchManningsChannelRoughnessCoeff',
      'Channel roughness coefficient for water erosion',
      5477, 1, 1, false, 1, 
      1, 'params.manningsChannelRoughnessCoeff', true);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.2, 0.0, 0.2, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchManningsSurfaceRoughnessCoeff',
      'Surface roughness coefficient for water erosion',
      5478, 1, 1, false, 1, 
      1, 'params.manningsSurfaceRoughnessCoeff', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.3, 0.0, 0.3, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxAnnualIrrVolumeAllowed_mm',
      'Maximum annual irrigation',
      5479, 1, 1, false, 1, 
      1, 'params.maxAnnualIrrVolumeAllowed_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 2000.0, 0.0, 2000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxApplicVolumeAutoIrr_mm',
      'Maximum volume per auto irrigation',
      5480, 1, 1, false, 1, 
      1, 'params.maxApplicVolumeAutoIrr_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 1000.0, 0.0, 1000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxFractionMaxNFertInOneApplic_frn',
      'Maximum fraction of annual N per auto fertilization',
      5481, 1, 1, false, 1, 
      1, 'params.maxFractionMaxNFertInOneApplic_frn', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxFractionOfRainfallInTimeOfConcParam',
      'Parameter for rainfall in time of concentration',
      5482, 1, 1, false, 1, 
      1, 'params.maxFractionOfRainfallInTimeOfConcParam', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 4.0, 0.0, 10.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxTillageDepth_m',
      'Maximum mixing depth so far',
      5483, 1, 1, true, 4, 
      1, 'state.maxTillageDepth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMaxWindErosionPerDay_tPha',
      'Maximum wind erosion allowed per day',
      5484, 1, 1, false, 1, 
      1, 'params.maxWindErosionPerDay_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 0.001, 0.0, 1000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanHeight_m',
      'Mean height of plants in patch today',
      5485, 1, 1, true, 4, 
      1, 'plantMeans.meanHeight_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanLeafAreaIndex',
      'Mean leaf area index of plants in patch today',
      5486, 1, 1, true, 4, 
      1, 'plantMeans.meanLeafAreaIndex', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanMinCropManagementFactor',
      'Mean minimum crop management factor of plants in patch today',
      5487, 1, 1, true, 4, 
      1, 'plantMeans.meanMinCropManagementFactor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 100.0, -1000000.0, 1000000.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanWindErosionFactorFlatResidue',
      'Mean wind erosion factor (flat residue) of plants in patch today',
      5488, 1, 1, true, 4, 
      1, 'plantMeans.meanWindErosionFactorFlatResidue', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 5.0, 0.0, 5.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanWindErosionFactorStandingDead',
      'Mean wind erosion factor (standing dead residue) of plants in patch today',
      5489, 1, 1, true, 4, 
      1, 'plantMeans.meanWindErosionFactorStandingDead', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 5.0, 0.0, 5.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMeanWindErosionFactorStandingLive',
      'Mean wind erosion factor (standing live biomass) of plants in patch today',
      5490, 1, 1, true, 4, 
      1, 'plantMeans.meanWindErosionFactorStandingLive', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 5.0, 0.0, 5.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMinApplicVolumeAutoIrr_mm',
      'Minimum volume per auto irrigation',
      5491, 1, 1, false, 1, 
      1, 'params.minApplicVolumeAutoIrr_mm', false);
  aspect.addUnitsAndBounds(0, 12, 1, 1, 2, 0.0, 500.0, 0.0, 500.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMineralPActiveAdsorbedToSediment_kgPha',
      'P as active mineral lost in eroded soil today',
      5492, 1, 1, true, 4, 
      2, 'movement.mineralPActiveAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMineralPStableAdsorbedToSediment_kgPha',
      'P as stable mineral lost in eroded soil today',
      5493, 1, 1, true, 4, 
      2, 'movement.mineralPStableAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMinimumMaxAnnualNFert_kgPha',
      'Lowest maximum annual N fertilizer of plants in patch today ',
      5494, 1, 1, true, 4, 
      2, 'plantMeans.minimumMaxAnnualNFert_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 10000.0, 0.0, 10000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMinIntervalAutoFert_days',
      'Minimum days between auto fertilizations',
      5495, 2, 1, false, 1, 
      1, 'params.minIntervalAutoFert_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 1000.0, 0.0, 1000.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMinIntervalAutoHarvest_days',
      'Minimum days between auto harvests',
      5496, 2, 1, false, 1, 
      1, 'params.minIntervalAutoHarvest_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMinIntervalAutoIrr_days',
      'Minimum days between auto irrigations',
      5497, 2, 1, false, 1, 
      1, 'params.minIntervalAutoIrr_days', false);
  aspect.addUnitsAndBounds(0, 23, 1, 1, 1, 0.0, 365.0, 0.0, 365.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMulchDepth_m',
      'Mulch depth',
      5498, 1, 1, false, 4, 
      1, 'mulch.depth_m', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 10.0, 0.0, 100.0, 2);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMulchDrawingColor',
      'Mulch color',
      5499, 7, 1, false, 1, 
      1, 'params.mulchDrawingColor', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMulchFlatCropResidue_tPha',
      'Mulch residue',
      5500, 1, 1, false, 2, 
      2, 'mulch.flatCropResidue_tPha', false);
  aspect.addUnitsAndBounds(0, 9, 2, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 4, 2, 6, 0.0, 0.000001, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMulchOrganicNFresh_kgPha',
      'Mulch N as fresh organic ',
      5501, 1, 1, false, 2, 
      2, 'mulch.organicNFresh_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchMulchOrganicPFresh_kgPha',
      'Mulch P as fresh organic ',
      5502, 1, 1, false, 2, 
      2, 'mulch.organicPFresh_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1000.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNFertAutoApplied_kgPha',
      'N fertilizer applied today',
      5503, 1, 1, true, 4, 
      2, 'movement.nFertAutoApplied_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNInIrrigationForDay_kgPha',
      'N as nitrate entering soil in irrigation today',
      5504, 1, 1, true, 4, 
      2, 'movement.nInIrrigationForDay_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNInPatchRainfallForDay_kgPha',
      'N as nitrate entering soil in rainfall today',
      5505, 1, 1, true, 4, 
      2, 'movement.nInPatchRainfallForDay_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNitrateAdsorbedToSediment_kgPha',
      'N as nitrate lost in eroded soil today',
      5506, 1, 1, true, 4, 
      2, 'movement.nitrateAdsorbedToSediment_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNitrateConcInIrrigationWater_gPm3',
      'N as nitrate concentration in irrigation water',
      5507, 1, 1, false, 1, 
      1, 'params.nitrateConcInIrrigationWater_gPm3', true);
  aspect.addUnitsAndBounds(0, 25, 1, 1, 1, 0.5, 1.5, 0.5, 1.5, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNitrateLostInRunoff_kgPha',
      'N as nitrate lost in runoff today',
      5508, 1, 1, true, 4, 
      2, 'movement.nitrateLostInRunoff_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNitrateMovedToFirstLayerFromEvaporation_kgPha',
      'N as nitrate moved to surface from evaporation today',
      5509, 1, 1, true, 4, 
      2, 'movement.nitrateMovedToFirstLayerFromEvaporation_kgPha', false);
  aspect.addUnitsAndBounds(0, 9, 1, 3, 9, 0.0, 1.0, 0.0, 1000000.0, 3);
  aspect.addUnitsAndBounds(2, 31, 1, 2, 5, 0.0, 100.0, 0.0, 5000.0, 3);
  aspect.addUnitsAndBounds(3, 6, 3, 2, 6, 0.0, 0.0, 0.0, 1000000.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNitrogenLeachingParam',
      'Fraction of porosity volume to consider when leaching nitrogen',
      5510, 1, 1, false, 1, 
      1, 'params.nitrogenLeachingParam', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 1.0, 0.0, 1.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNStressFactorToTriggerAutoFert',
      'Nitrogen stress factor to trigger auto fertilization',
      5511, 1, 1, false, 1, 
      1, 'params.nStressFactorToTriggerAutoFert', false);
  aspect.addUnitsAndBounds(0, 26, 1, 1, 1, 0.0, 0.95, 0.0, 0.95, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNumLayers',
      'Number of soil layers',
      5512, 2, 1, true, 4, 
      1, 'state.numLayers', false);
  aspect.addUnitsAndBounds(0, 1, 1, 1, 1, 0.0, 10.0, 0.0, 10.0, 3);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchNVolatilizationByDepthCoeffs',
      'S Curve - effect of soil depth on nitrogen volatilization (loss of ammonia)',
      5513, 1, 4, false, 1, 
      3, 'params.nVolatilizationByDepthCoeffs', false);
  aspect.addUnitsAndBounds(0, 2, 4, 4, 7, 0.0, 3.0, 0.0, 3.0, 1);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowActiveAndStableHumusNFlow',
      'Allow flow between active and stable humus N',
      5514, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowActiveAndStableHumusNFlow]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowActiveAndStableMineralPFlow',
      'Allow flow between active and stable mineral P',
      5515, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowActiveAndStableMineralPFlow]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowActiveHumusNMineralization',
      'Allow mineralization of active humus N',
      5516, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowActiveHumusNMineralization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowActiveHumusPMineralization',
      'Allow mineralization of active humus P',
      5517, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowActiveHumusPMineralization]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowDenitrification',
      'Allow denitrification (loss of nitrate)',
      5518, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowDenitrification]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeAmmonia',
      'Allow ammonia to be lost in eroded soil',
      5519, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeAmmonia]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeFlatCropResidue',
      'Allow flat residue to be lost in eroded soil',
      5520, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeFlatCropResidue]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeLabileP',
      'Allow labile P to be lost in eroded soil',
      5521, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeLabileP]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeMineralPActive',
      'Allow active mineral P to be lost in eroded soil',
      5522, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeMineralPActive]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeMineralPStable',
      'Allow stable mineral P to be lost in eroded soil',
      5523, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeMineralPStable]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeNitrate',
      'Allow nitrate to be lost in eroded soil',
      5524, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeNitrate]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicMatter',
      'Allow organic matter to be lost in eroded soil',
      5525, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicMatter]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicNActiveHumus',
      'Allow active humus organic N to be lost in eroded soil',
      5526, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicNActiveHumus]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicNFresh',
      'Allow fresh organic N to be lost in eroded soil',
      5527, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicNFresh]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicNStableHumus',
      'Allow stable humus organic N to be lost in eroded soil',
      5528, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicNStableHumus]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicPFresh',
      'Allow fresh organic P to be lost in eroded soil',
      5529, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicPFresh]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
  aspect := GsAspect.createWithInfo('kSoilPatchOptionsAllowErodedSoilToTakeOrganicPHumus',
      'Allow humus organic P to be lost in eroded soil',
      5530, 8, 1, false, 1, 
      1, 'options[kSoilOptionsAllowErodedSoilToTakeOrganicPHumus]', false);
  aspect.addUnitsAndBounds(0, 30, 1, 1, 1, 0.0, 0.0, 0.0, 0.0, 0);
  aspectManager.addAspect(aspect);
    end;

end.
